<a href="https://colab.research.google.com/github/Docdoi/AI-Engineered_Nanoproteins_A_De_Novo_Approach_to_Inhibit_Hantavirus_Transmission-/blob/main/Diffusion2_6y5wB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Clone RFdiffusion original
%cd /content

!git clone https://github.com/RosettaCommons/RFdiffusion.git

%cd /content/RFdiffusion

/content
Cloning into 'RFdiffusion'...
remote: Enumerating objects: 759, done.
remote: Counting objects: 100% (507/507), done.
remote: Compressing objects: 100% (306/306), done.
remote: Total 759 (delta 334), reused 202 (delta 200), pack-reused 252 (from 2)
Receiving objects: 100% (759/759), 10.19 MiB | 8.16 MiB/s, done.
Resolving deltas: 100% (389/389), done.
/content/RFdiffusion

In [2]:
#Install micromamba
%cd /content

!mkdir -p /content/bin
!curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest \
  | tar -xvj -C /content/bin --strip-components=1 bin/micromamba

!/content/bin/micromamba --version

/content
bin/micromamba
2.9.0

In [3]:
#Python 3.9 environment
!/content/bin/micromamba create -y \
  -p /content/rfd1_env \
  -c conda-forge \
  python=3.9 \
  pip

[+] 0.0s
Fetch Shard Index for conda-forge/linux-64                                                ✔ Done (0.1 sec)
Fetch Shard Index for conda-forge/noarch                                                  ✔ Done (0.1 sec)
Fetching and Parsing Packages' Shards                                                     ✔ Done (5.4 sec)

Resolving Environment                                                                     ✔ Done (0.2 sec)

Transaction

  Prefix: /content/rfd1_env

  Updating specs:

   - python=3.9
   - pip


  Package               Version  Build                 Channel          Size
──────────────────────────────────────────────────────────────────────────────
  Install:
──────────────────────────────────────────────────────────────────────────────

  + _openmp_mutex           4.5  20_gnu                conda-forge      29kB
  + bzip2                 1.0.8  hda65f42_10           conda-forge     258kB
  + ca-certificates   2026.7.22  hbd8a1cb_0            conda-forge     132kB
  + icu                    78.3  py310h44b86e0_2       conda-forge      14MB
  + ld_impl_linux-64     2.46.1  default_hbd61a6d_102  conda-forge     745kB
  + libexpat              2.8.1  hecca717_1            conda-forge      78kB
  + libffi                3.7.0  h3435931_0            conda-forge      68kB
  + libgcc               16.1.0  ha9f2e26_3            conda-forge       1MB
  + libgomp              16.1.0  he0feb66_3            conda-forge     642kB
  + liblzma               5.8.3  hb03c661_1            conda-forge     113kB
  + libnsl                2.0.1  hb9d3cd8_1            conda-forge      34kB
  + libsqlite            3.53.4  h13e7031_1            conda-forge     974kB
  + libstdcxx            16.1.0  h934c35e_3            conda-forge       7MB
  + libuuid              2.42.2  h5347b49_0            conda-forge      40kB
  + libxcrypt            4.4.38  h280c20c_0            conda-forge     102kB
  + libzlib               1.3.2  h25fd6f3_3            conda-forge      64kB
  + ncurses                 6.6  hdb14827_1            conda-forge     911kB
  + openssl               3.6.3  h35e630c_1            conda-forge       3MB
  + pip                    25.2  pyh8b19718_0          conda-forge       1MB
  + python               3.9.23  hc30ae73_0_cpython    conda-forge      24MB
  + readline                8.3  hd6e31c0_1            conda-forge     349kB
  + setuptools           80.9.0  pyhff2d567_0          conda-forge     749kB
  + tk                   8.6.13  noxft_h1df4ec4_4      conda-forge       4MB
  + tzdata                2026c  h151e31d_0            conda-forge     119kB
  + wheel                0.45.1  pyhd8ed1ab_1          conda-forge      63kB
  + zstd                  1.5.7  hb78ec9c_7            conda-forge     601kB

  Summary:

  Install: 26 packages

  Total download: 60MB

──────────────────────────────────────────────────────────────────────────────


warning  libmamba Security Warning: This transaction includes executing package scripts (pre/post-link/unlink) if present. These scripts can contain arbitrary code. Please ensure you trust the package sources.

Transaction starting
[+] 0.0s
Downloading        5%
Extracting         0%libstdcxx                                            6.6MB @  46.7MB/s  0.0s
openssl                                              3.2MB @  ??.?MB/s  0.0s
tk                                                   3.6MB @  ??.?MB/s  0.0s
[+] 0.1s
Downloading  (5)  27%
Extracting         0%pip                                                  1.2MB @  ??.?MB/s  0.0s
libgcc                                               1.1MB @  ??.?MB/s  0.0s
libsqlite                                          974.3kB @  18.1MB/s  0.1s
ncurses                                            911.2kB @  ??.?MB/s  0.0s
setuptools                                         748.8kB @  ??.?MB/s  0.1s
ld_impl_linux-64                                   745.3kB @  ??.?MB/s  0.0s
libgomp                                            641.5kB @  ??.?MB/s  0.0s
[+] 0.2s
Downloading  (5)  72%
Extracting   (8)  ⣾  icu                                                 14.5MB @  68.6MB/s  0.2s
bzip2                                              257.8kB @  ??.?MB/s  0.0s
readline                                           348.9kB @  ??.?MB/s  0.0s
zstd                                               601.3kB @  ??.?MB/s  0.0s
ca-certificates                                    131.8kB @  ??.?MB/s  0.0s
liblzma                                            113.0kB @  ??.?MB/s  0.0s
tzdata                                             118.8kB @  ??.?MB/s  0.0s
libxcrypt                                          102.0kB @  ??.?MB/s  0.0s
libexpat                                            77.9kB @  ??.?MB/s  0.0s
libffi                                              67.6kB @  ??.?MB/s  0.0s
python                                              23.7MB @  82.5MB/s  0.2s
wheel                                               62.9kB @  ??.?MB/s  0.0s
libzlib                                             63.7kB @  ??.?MB/s  0.0s
libuuid                                             40.0kB @  ??.?MB/s  0.0s
[+] 0.3s
Downloading  (2) 100%
Extracting  (22)  ⣾  libnsl                                              33.7kB @  ??.?MB/s  0.0s
_openmp_mutex                                       28.9kB @  ??.?MB/s  0.0s
[+] 0.4s
Downloading      100%
Extracting  (22)  ⣾  [+] 0.5s
Downloading      100%
Extracting  (20)  ⣾  [+] 0.6s
Downloading      100%
Extracting  (16)  ⣾  [+] 0.7s
Downloading      100%
Extracting  (14)  ⣾  [+] 0.8s
Downloading      100%
Extracting  (11)  ⣾  [+] 0.9s
Downloading      100%
Extracting  (11)  ⣾  [+] 1.0s
Downloading      100%
Extracting  (10)  ⣾  [+] 1.1s
Downloading      100%
Extracting  (10)  ⣾  [+] 1.2s
Downloading      100%
Extracting  (10)  ⣾  [+] 1.3s
Downloading      100%
Extracting   (5)  ⣾  [+] 1.4s
Downloading      100%
Extracting   (1)  ⣾  Linking libzlib-1.3.2-h25fd6f3_3
Linking libgomp-16.1.0-he0feb66_3
Linking zstd-1.5.7-hb78ec9c_7
Linking _openmp_mutex-4.5-20_gnu
Linking ld_impl_linux-64-2.46.1-default_hbd61a6d_102
Linking libgcc-16.1.0-ha9f2e26_3
Linking libstdcxx-16.1.0-h934c35e_3
Linking bzip2-1.0.8-hda65f42_10
Linking libnsl-2.0.1-hb9d3cd8_1
Linking libexpat-2.8.1-hecca717_1
Linking libuuid-2.42.2-h5347b49_0
Linking libffi-3.7.0-h3435931_0
Linking libxcrypt-4.4.38-h280c20c_0
Linking liblzma-5.8.3-hb03c661_1
Linking ncurses-6.6-hdb14827_1
Linking tk-8.6.13-noxft_h1df4ec4_4
Linking icu-78.3-py310h44b86e0_2
Linking readline-8.3-hd6e31c0_1
Linking libsqlite-3.53.4-h13e7031_1
Linking tzdata-2026c-h151e31d_0
Linking ca-certificates-2026.7.22-hbd8a1cb_0
Linking openssl-3.6.3-h35e630c_1
Linking python-3.9.23-hc30ae73_0_cpython
Linking wheel-0.45.1-pyhd8ed1ab_1
Linking setuptools-80.9.0-pyhff2d567_0
Linking pip-25.2-pyh8b19718_0

Transaction finished


To activate this environment, use:

    micromamba activate /content/rfd1_env

Or to execute a single command in this environment, use:

    micromamba run -p /content/rfd1_env mycommand

In [4]:
!/content/bin/micromamba run \
  -p /content/rfd1_env \
  python --version

Python 3.9.23

In [5]:
#PyTorch 1.12.1 + CUDA 11.6
!/content/bin/micromamba run \
  -p /content/rfd1_env \
  pip install --no-cache-dir \
  "numpy<2" \
  torch==1.12.1+cu116 \
  --extra-index-url https://download.pytorch.org/whl/cu116

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu116
Collecting numpy<2
  Downloading numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting torch==1.12.1+cu116
  Downloading https://download-r2.pytorch.org/whl/cu116/torch-1.12.1%2Bcu116-cp39-cp39-linux_x86_64.whl (1904.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 GB 240.4 MB/s  0:00:10
Collecting typing-extensions (from torch==1.12.1+cu116)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Downloading numpy-1.26.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 216.0 MB/s  0:00:00
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Installing collected packages: typing-extensions, numpy, torch
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [torch]
Successfully installed numpy-1.26.4 torch-1.12.1+cu116 typing-extensions-4.16.0

In [6]:
!/content/bin/micromamba run \
  -p /content/rfd1_env \
  python -c "import torch; print('Torch:', torch.__version__); print('CUDA:', torch.version.cuda); print('CUDA available:', torch.cuda.is_available()); print('GPU:', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'NONE')"

Torch: 1.12.1+cu116
CUDA: 11.6
CUDA available: True
GPU: Tesla T4

In [7]:
#DGL 1.0.2 cu116
!/content/bin/micromamba run \
  -p /content/rfd1_env \
  pip install --no-cache-dir \
  dgl==1.0.2+cu116 \
  -f https://data.dgl.ai/wheels/cu116/repo.html

Looking in links: https://data.dgl.ai/wheels/cu116/repo.html
Collecting dgl==1.0.2+cu116
  Downloading https://data.dgl.ai/wheels/cu116/dgl-1.0.2%2Bcu116-cp39-cp39-manylinux1_x86_64.whl (265.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.8/265.8 MB 397.6 MB/s  0:00:00
Requirement already satisfied: numpy>=1.14.0 in ./rfd1_env/lib/python3.9/site-packages (from dgl==1.0.2+cu116) (1.26.4)
Collecting scipy>=1.1.0 (from dgl==1.0.2+cu116)
  Downloading scipy-1.13.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting networkx>=2.1 (from dgl==1.0.2+cu116)
  Downloading networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
Collecting requests>=2.19.0 (from dgl==1.0.2+cu116)
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting tqdm (from dgl==1.0.2+cu116)
  Downloading tqdm-4.70.0-py3-none-any.whl.metadata (57 kB)
Collecting psutil>=5.8.0 (from dgl==1.0.2+cu116)
  Downloading psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl.metadata (22 kB)
Collecting charset_normalizer<4,>=2 (from requests>=2.19.0->dgl==1.0.2+cu116)
  Downloading charset_normalizer-3.5.1-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (45 kB)
Collecting idna<4,>=2.5 (from requests>=2.19.0->dgl==1.0.2+cu116)
  Downloading idna-3.19-py3-none-any.whl.metadata (9.2 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.19.0->dgl==1.0.2+cu116)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2017.4.17 (from requests>=2.19.0->dgl==1.0.2+cu116)
  Downloading certifi-2026.7.22-py3-none-any.whl.metadata (2.5 kB)
Downloading networkx-3.2.1-py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 210.3 MB/s  0:00:00
Downloading psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl (155 kB)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.5.1-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (262 kB)
Downloading idna-3.19-py3-none-any.whl (68 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Downloading certifi-2026.7.22-py3-none-any.whl (136 kB)
Downloading scipy-1.13.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 218.7 MB/s  0:00:00
Downloading tqdm-4.70.0-py3-none-any.whl (80 kB)
Installing collected packages: urllib3, tqdm, scipy, psutil, networkx, idna, charset_normalizer, certifi, requests, dgl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/10 [dgl]
Successfully installed certifi-2026.7.22 charset_normalizer-3.5.1 dgl-1.0.2+cu116 idna-3.19 networkx-3.2.1 psutil-7.2.2 requests-2.32.5 scipy-1.13.1 tqdm-4.70.0 urllib3-2.6.3

In [8]:
!/content/bin/micromamba run \
  -p /content/rfd1_env \
  python -c "import dgl; print('DGL:', dgl.__version__)"

DGL backend not selected or invalid.  Assuming PyTorch for now.
Setting the default backend to "pytorch". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/content/rfd1_env/lib/python3.9/site-packages/dgl/__init__.py", line 18, in <module>
    from .backend import load_backend, backend_name
  File "/content/rfd1_env/lib/python3.9/site-packages/dgl/backend/__init__.py", line 122, in <module>
    load_backend(get_preferred_backend())
  File "/content/rfd1_env/lib/python3.9/site-packages/dgl/backend/__init__.py", line 51, in load_backend
    from .._ffi.base import load_tensor_adapter  # imports DGL C library
  File "/content/rfd1_env/lib/python3.9/site-packages/dgl/_ffi/base.py", line 50, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
  File "/content/rfd1_env/lib/python3.9/site-packages/dgl/_ffi/base.py", line 39, in _load_lib
    lib = ctypes.CDLL(lib_path[0])
  File "/content/rfd1_env/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcusparse.so.11: cannot open shared object file: No such file or directory

In [9]:
!/content/bin/micromamba install -y \
  -p /content/rfd1_env \
  -c conda-forge \
  cudatoolkit=11.6

Using Cached Shard Index for conda-forge/linux-64                                                   ✔ Done
Using Cached Shard Index for conda-forge/noarch                                                     ✔ Done
Fetching and Parsing Packages' Shards                                                     ✔ Done (0.3 sec)

Pinned packages:

  - python=3.9

Resolving Environment                                                                     ✔ Done (0.1 sec)

Transaction

  Prefix: /content/rfd1_env

  Updating specs:

   - cudatoolkit=11.6


  Package         Version  Build        Channel          Size
───────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────

  + cudatoolkit    11.6.2  hfc3e2af_13  conda-forge     628MB
  + libgcc-ng      16.1.0  h69a702a_3   conda-forge      28kB
  + libstdcxx-ng   16.1.0  hdf11a46_3   conda-forge      28kB

  Summary:

  Install: 3 packages

  Total download: 628MB

───────────────────────────────────────────────────────────────


warning  libmamba Security Warning: This transaction includes executing package scripts (pre/post-link/unlink) if present. These scripts can contain arbitrary code. Please ensure you trust the package sources.

Transaction starting
[+] 0.0s
Downloading        5%
Extracting         0%libgcc-ng                                           ??.?MB @  ??.?MB/s  0.0s
libstdcxx-ng                                        28.3kB @  ??.?MB/s  0.0s
[+] 0.1s
Downloading  (1)   1%
Extracting        67%[+] 0.2s
Downloading  (1)   3%
Extracting        67%[+] 0.3s
Downloading  (1)   4%
Extracting        67%[+] 0.4s
Downloading  (1)   5%
Extracting        67%[+] 0.5s
Downloading  (1)   6%
Extracting        67%[+] 0.6s
Downloading  (1)   7%
Extracting        67%[+] 0.7s
Downloading  (1)   8%
Extracting        67%[+] 0.8s
Downloading  (1)  10%
Extracting        67%[+] 0.9s
Downloading  (1)  11%
Extracting        67%[+] 1.0s
Downloading  (1)  12%
Extracting        67%[+] 1.1s
Downloading  (1)  13%
Extracting        67%[+] 1.2s
Downloading  (1)  14%
Extracting        67%[+] 1.3s
Downloading  (1)  15%
Extracting        67%[+] 1.4s
Downloading  (1)  16%
Extracting        67%[+] 1.5s
Downloading  (1)  18%
Extracting        67%[+] 1.6s
Downloading  (1)  18%
Extracting        67%[+] 1.7s
Downloading  (1)  19%
Extracting        67%[+] 1.8s
Downloading  (1)  20%
Extracting        67%[+] 1.9s
Downloading  (1)  22%
Extracting        67%[+] 2.0s
Downloading  (1)  23%
Extracting        67%[+] 2.1s
Downloading  (1)  24%
Extracting        67%[+] 2.2s
Downloading  (1)  25%
Extracting        67%[+] 2.3s
Downloading  (1)  26%
Extracting        67%[+] 2.4s
Downloading  (1)  27%
Extracting        67%[+] 2.5s
Downloading  (1)  28%
Extracting        67%[+] 2.6s
Downloading  (1)  29%
Extracting        67%[+] 2.7s
Downloading  (1)  30%
Extracting        67%[+] 2.8s
Downloading  (1)  31%
Extracting        67%[+] 2.9s
Downloading  (1)  32%
Extracting        67%[+] 3.0s
Downloading  (1)  33%
Extracting        67%[+] 3.1s
Downloading  (1)  35%
Extracting        67%[+] 3.2s
Downloading  (1)  36%
Extracting        67%[+] 3.3s
Downloading  (1)  37%
Extracting        67%[+] 3.4s
Downloading  (1)  38%
Extracting        67%[+] 3.5s
Downloading  (1)  39%
Extracting        67%[+] 3.6s
Downloading  (1)  40%
Extracting        67%[+] 3.7s
Downloading  (1)  41%
Extracting        67%[+] 3.8s
Downloading  (1)  42%
Extracting        67%[+] 3.9s
Downloading  (1)  43%
Extracting        67%[+] 4.0s
Downloading  (1)  44%
Extracting        67%[+] 4.1s
Downloading  (1)  45%
Extracting        67%[+] 4.2s
Downloading  (1)  45%
Extracting        67%[+] 4.3s
Downloading  (1)  46%
Extracting        67%[+] 4.4s
Downloading  (1)  47%
Extracting        67%[+] 4.5s
Downloading  (1)  48%
Extracting        67%[+] 4.6s
Downloading  (1)  49%
Extracting        67%[+] 4.7s
Downloading  (1)  50%
Extracting        67%[+] 4.8s
Downloading  (1)  51%
Extracting        67%[+] 4.9s
Downloading  (1)  52%
Extracting        67%[+] 5.0s
Downloading  (1)  53%
Extracting        67%[+] 5.1s
Downloading  (1)  54%
Extracting        67%[+] 5.2s
Downloading  (1)  55%
Extracting        67%[+] 5.3s
Downloading  (1)  56%
Extracting        67%[+] 5.4s
Downloading  (1)  57%
Extracting        67%[+] 5.5s
Downloading  (1)  58%
Extracting        67%[+] 5.6s
Downloading  (1)  59%
Extracting        67%[+] 5.7s
Downloading  (1)  60%
Extracting        67%[+] 5.8s
Downloading  (1)  61%
Extracting        67%[+] 5.9s
Downloading  (1)  62%
Extracting        67%[+] 6.0s
Downloading  (1)  63%
Extracting        67%[+] 6.1s
Downloading  (1)  64%
Extracting        67%[+] 6.2s
Downloading  (1)  65%
Extracting        67%[+] 6.3s
Downloading  (1)  66%
Extracting        67%[+] 6.4s
Downloading  (1)  67%
Extracting        67%[+] 6.5s
Downloading  (1)  68%
Extracting        67%[+] 6.6s
Downloading  (1)  69%
Extracting        67%[+] 6.7s
Downloading  (1)  70%
Extracting        67%[+] 6.8s
Downloading  (1)  71%
Extracting        67%[+] 6.9s
Downloading  (1)  72%
Extracting        67%[+] 7.0s
Downloading  (1)  73%
Extracting        67%[+] 7.1s
Downloading  (1)  74%
Extracting        67%[+] 7.2s
Downloading  (1)  75%
Extracting        67%[+] 7.3s
Downloading  (1)  76%
Extracting        67%[+] 7.4s
Downloading  (1)  77%
Extracting        67%[+] 7.5s
Downloading  (1)  78%
Extracting        67%[+] 7.6s
Downloading  (1)  79%
Extracting        67%[+] 7.7s
Downloading  (1)  79%
Extracting        67%[+] 7.8s
Downloading  (1)  80%
Extracting        67%[+] 7.9s
Downloading  (1)  81%
Extracting        67%[+] 8.0s
Downloading  (1)  82%
Extracting        67%[+] 8.1s
Downloading  (1)  83%
Extracting        67%[+] 8.2s
Downloading  (1)  84%
Extracting        67%[+] 8.3s
Downloading  (1)  85%
Extracting        67%[+] 8.4s
Downloading  (1)  86%
Extracting        67%[+] 8.5s
Downloading  (1)  87%
Extracting        67%[+] 8.6s
Downloading  (1)  88%
Extracting        67%[+] 8.7s
Downloading  (1)  89%
Extracting        67%[+] 8.8s
Downloading  (1)  90%
Extracting        67%[+] 8.9s
Downloading  (1)  90%
Extracting        67%[+] 9.0s
Downloading  (1)  92%
Extracting        67%[+] 9.1s
Downloading  (1)  93%
Extracting        67%[+] 9.2s
Downloading  (1)  94%
Extracting        67%[+] 9.3s
Downloading  (1)  95%
Extracting        67%[+] 9.4s
Downloading  (1)  96%
Extracting        67%[+] 9.5s
Downloading  (1)  97%
Extracting        67%[+] 9.6s
Downloading  (1)  98%
Extracting        67%[+] 9.7s
Downloading  (1)  99%
Extracting        67%[+] 9.8s
Downloading  (1) 100%
Extracting        67%cudatoolkit                                        627.9MB @  63.7MB/s  9.8s
[+] 9.9s
Downloading      100%
Extracting        67%[+] 10.0s
Downloading      100%
Extracting        67%[+] 10.1s
Downloading      100%
Extracting        67%[+] 10.2s
Downloading      100%
Extracting        67%[+] 10.3s
Downloading      100%
Extracting        67%[+] 10.4s
Downloading      100%
Extracting        67%[+] 10.5s
Downloading      100%
Extracting        67%[+] 10.6s
Downloading      100%
Extracting        67%[+] 10.7s
Downloading      100%
Extracting        67%[+] 10.8s
Downloading      100%
Extracting        67%[+] 10.9s
Downloading      100%
Extracting        67%[+] 11.0s
Downloading      100%
Extracting        67%[+] 11.1s
Downloading      100%
Extracting        67%[+] 11.2s
Downloading      100%
Extracting        67%[+] 11.3s
Downloading      100%
Extracting        67%[+] 11.4s
Downloading      100%
Extracting        67%[+] 11.5s
Downloading      100%
Extracting        67%[+] 11.6s
Downloading      100%
Extracting        67%[+] 11.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 11.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 11.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 12.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 12.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 12.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 12.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 12.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 12.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 12.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 12.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 12.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 12.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 13.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 13.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 13.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 13.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 13.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 13.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 13.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 13.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 13.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 13.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 14.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 14.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 14.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 14.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 14.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 14.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 14.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 14.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 14.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 14.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 15.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 15.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 15.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 15.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 15.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 15.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 15.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 15.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 15.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 15.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 16.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 16.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 16.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 16.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 16.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 16.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 16.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 16.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 16.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 16.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 17.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 17.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 17.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 17.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 17.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 17.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 17.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 17.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 17.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 17.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 18.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 18.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 18.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 18.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 18.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 18.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 18.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 18.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 18.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 18.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 19.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 19.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 19.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 19.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 19.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 19.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 19.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 19.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 19.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 19.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 20.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 20.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 20.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 20.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 20.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 20.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 20.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 20.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 20.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 20.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 21.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 21.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 21.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 21.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 21.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 21.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 21.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 21.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 21.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 21.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 22.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 22.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 22.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 22.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 22.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 22.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 22.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 22.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 22.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 22.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 23.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 23.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 23.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 23.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 23.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 23.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 23.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 23.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 23.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 23.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 24.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 24.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 24.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 24.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 24.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 24.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 24.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 24.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 24.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 24.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 25.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 25.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 25.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 25.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 25.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 25.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 25.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 25.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 25.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 25.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 26.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 26.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 26.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 26.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 26.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 26.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 26.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 26.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 26.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 26.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 27.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 27.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 27.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 27.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 27.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 27.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 27.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 27.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 27.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 27.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 28.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 28.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 28.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 28.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 28.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 28.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 28.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 28.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 28.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 28.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 29.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 29.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 29.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 29.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 29.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 29.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 29.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 29.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 29.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 29.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 30.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 30.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 30.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 30.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 30.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 30.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 30.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 30.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 30.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 30.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 31.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 31.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 31.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 31.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 31.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 31.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 31.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 31.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 31.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 31.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 32.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 32.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 32.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 32.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 32.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 32.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 32.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 32.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 32.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 32.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 33.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 33.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 33.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 33.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 33.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 33.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 33.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 33.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 33.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 33.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 34.0s
Downloading      100%
Extracting   (1)  ⣾  [+] 34.1s
Downloading      100%
Extracting   (1)  ⣾  [+] 34.2s
Downloading      100%
Extracting   (1)  ⣾  [+] 34.3s
Downloading      100%
Extracting   (1)  ⣾  [+] 34.4s
Downloading      100%
Extracting   (1)  ⣾  [+] 34.5s
Downloading      100%
Extracting   (1)  ⣾  [+] 34.6s
Downloading      100%
Extracting   (1)  ⣾  [+] 34.7s
Downloading      100%
Extracting   (1)  ⣾  [+] 34.8s
Downloading      100%
Extracting   (1)  ⣾  [+] 34.9s
Downloading      100%
Extracting   (1)  ⣾  [+] 35.0s

In [10]:
!find /content/rfd1_env -name "libcusparse.so*" -print

/content/rfd1_env/lib/libcusparse.so.11.7.2.124
/content/rfd1_env/lib/libcusparse.so.11
/content/rfd1_env/lib/libcusparse.so

In [11]:
!DGLBACKEND=pytorch \
LD_LIBRARY_PATH=/content/rfd1_env/lib:$LD_LIBRARY_PATH \
/content/bin/micromamba run \
-p /content/rfd1_env \
python -c "import dgl; print('DGL:', dgl.__version__)"

DGL: 1.0.2+cu116

In [12]:
!DGLBACKEND=pytorch \
LD_LIBRARY_PATH=/content/rfd1_env/lib:$LD_LIBRARY_PATH \
/content/bin/micromamba run \
-p /content/rfd1_env \
python -c "import torch,dgl; print('Torch:',torch.__version__); print('CUDA:',torch.version.cuda); print('GPU:',torch.cuda.get_device_name(0)); print('DGL:',dgl.__version__); print('Torch + DGL OK')"

Torch: 1.12.1+cu116
CUDA: 11.6
GPU: Tesla T4
DGL: 1.0.2+cu116
Torch + DGL OK

In [13]:
#SE3Transformer for RFdiffusion original

%cd /content/RFdiffusion

!DGLBACKEND=pytorch \
LD_LIBRARY_PATH=/content/rfd1_env/lib:$LD_LIBRARY_PATH \
/content/bin/micromamba run \
-p /content/rfd1_env \
pip install --no-cache-dir ./env/SE3Transformer

/content/RFdiffusion
Processing ./env/SE3Transformer
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: se3-transformer
  DEPRECATION: Building 'se3-transformer' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'se3-transformer'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  Building wheel for se3-transformer (setup.py) ... done
  Created wheel for se3-transformer: filename=se3_transformer-1.0.0-py3-none-any.whl size=50903 sha256=e8db1255ae4db97bde54a43593f818946f8e92625d790d79b8dc5101e1f85348
  Stored in directory: /tmp/pip-ephem-wheel-cache-80bvdayi/wheels/4a/c4/78/528d473126524a5137099365ef33372dbe5a8b614e12973b1d
Successfully built se3-transformer
Installing collected packages: se3-transformer
Successfully installed se3-transformer-1.0.0

In [14]:
!DGLBACKEND=pytorch \
LD_LIBRARY_PATH=/content/rfd1_env/lib:$LD_LIBRARY_PATH \
/content/bin/micromamba run \
-p /content/rfd1_env \
python -c "import se3_transformer; print('SE3Transformer import OK')"

SE3Transformer import OK

In [15]:
#left dependency

!/content/bin/micromamba run \
-p /content/rfd1_env \
pip install --no-cache-dir \
e3nn==0.3.3 \
hydra-core==1.3.2 \
pyrsistent==0.19.3 \
decorator==5.1.0 \
icecream \
scipy \
opt_einsum

Collecting e3nn==0.3.3
  Downloading e3nn-0.3.3-py3-none-any.whl.metadata (5.0 kB)
Collecting hydra-core==1.3.2
  Downloading hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Collecting pyrsistent==0.19.3
  Downloading pyrsistent-0.19.3-py3-none-any.whl.metadata (27 kB)
Collecting decorator==5.1.0
  Downloading decorator-5.1.0-py3-none-any.whl.metadata (3.9 kB)
Collecting icecream
  Downloading icecream-2.2.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: scipy in /content/rfd1_env/lib/python3.9/site-packages (1.13.1)
Collecting opt_einsum
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Collecting sympy (from e3nn==0.3.3)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: torch>=1.8.0 in /content/rfd1_env/lib/python3.9/site-packages (from e3nn==0.3.3) (1.12.1+cu116)
Collecting opt-einsum-fx (from e3nn==0.3.3)
  Downloading opt_einsum_fx-0.1.4-py3-none-any.whl.metadata (3.3 kB)
Collecting omegaconf<2.4,>=2.2 (from hydra-core==1.3.2)
  Downloading omegaconf-2.3.1-py3-none-any.whl.metadata (4.5 kB)
Collecting antlr4-python3-runtime==4.9.* (from hydra-core==1.3.2)
  Downloading antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
  Preparing metadata (setup.py) ... done
Collecting packaging (from hydra-core==1.3.2)
  Downloading packaging-26.3-py3-none-any.whl.metadata (3.5 kB)
Collecting PyYAML>=5.1.0 (from omegaconf<2.4,>=2.2->hydra-core==1.3.2)
  Downloading pyyaml-6.0.3-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting colorama>=0.3.9 (from icecream)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting pygments>=2.2.0 (from icecream)
  Downloading pygments-2.21.0-py3-none-any.whl.metadata (2.5 kB)
Collecting executing>=2.1.0 (from icecream)
  Downloading executing-2.2.1-py2.py3-none-any.whl.metadata (8.9 kB)
Collecting asttokens>=2.0.1 (from icecream)
  Downloading asttokens-3.0.2-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: numpy<2.3,>=1.22.4 in /content/rfd1_env/lib/python3.9/site-packages (from scipy) (1.26.4)
Requirement already satisfied: typing-extensions in /content/rfd1_env/lib/python3.9/site-packages (from torch>=1.8.0->e3nn==0.3.3) (4.16.0)
Collecting mpmath<1.4,>=1.1.0 (from sympy->e3nn==0.3.3)
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Downloading e3nn-0.3.3-py3-none-any.whl (382 kB)
Downloading hydra_core-1.3.2-py3-none-any.whl (154 kB)
Downloading pyrsistent-0.19.3-py3-none-any.whl (57 kB)
Downloading decorator-5.1.0-py3-none-any.whl (9.1 kB)
Downloading omegaconf-2.3.1-py3-none-any.whl (79 kB)
Downloading icecream-2.2.0-py3-none-any.whl (16 kB)
Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Downloading asttokens-3.0.2-py3-none-any.whl (28 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading executing-2.2.1-py2.py3-none-any.whl (28 kB)
Downloading pygments-2.21.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 403.3 MB/s  0:00:00
Downloading pyyaml-6.0.3-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (750 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 750.8/750.8 kB 786.8 MB/s  0:00:00
Downloading opt_einsum_fx-0.1.4-py3-none-any.whl (13 kB)
Downloading packaging-26.3-py3-none-any.whl (129 kB)
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 596.3 MB/s  0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 661.4 MB/s  0:00:00
Building wheels for collected packages: antlr4-python3-runtime
  DEPRECATION: Building 'antlr4-python3-runtime' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'antlr4-python3-runtime'. Discussion can be found at https://github.com/pypa/pip/issues/6334
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144591 sha256=8e394437b1a3ab0fd94bb2f1ce10fa5134917cc4d64966821e5578384b72b07b
  Stored in directory: /tmp/pip-ephem-wheel-cache-7k18yk2d/wheels/23/cf/80/f3efa822e6ab23277902ee9165fe772eeb1dfb8014f359020a
Successfully built antlr4-python3-runtime
Installing collected packages: mpmath, antlr4-python3-runtime, sympy, PyYAML, pyrsistent, pygments, packaging, opt_einsum, executing, decorator, colorama, asttokens, opt-einsum-fx, omegaconf, icecream, hydra-core, e3nn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17/17 [e3nn]
Successfully installed PyYAML-6.0.3 antlr4-python3-runtime-4.9.3 asttokens-3.0.2 colorama-0.4.6 decorator-5.1.0 e3nn-0.3.3 executing-2.2.1 hydra-core-1.3.2 icecream-2.2.0 mpmath-1.3.0 omegaconf-2.3.1 opt-einsum-fx-0.1.4 opt_einsum-3.4.0 packaging-26.3 pygments-2.21.0 pyrsistent-0.19.3 sympy-1.14.0

In [16]:
#setting RFdiffusion original

%cd /content/RFdiffusion

!/content/bin/micromamba run \
-p /content/rfd1_env \
pip install -e . --no-deps

/content/RFdiffusion
Obtaining file:///content/RFdiffusion
  Preparing metadata (setup.py) ... done
Installing collected packages: rfdiffusion
  DEPRECATION: Legacy editable install of rfdiffusion==1.1.0 from file:///content/RFdiffusion (setup.py develop) is deprecated. pip 25.3 will enforce this behaviour change. A possible replacement is to add a pyproject.toml or enable --use-pep517, and use setuptools >= 64. If the resulting installation is not behaving as expected, try using --config-settings editable_mode=compat. Please consult the setuptools documentation for more information. Discussion can be found at https://github.com/pypa/pip/issues/11457
  Running setup.py develop for rfdiffusion
Successfully installed rfdiffusion-1.1.0

In [17]:
!DGLBACKEND=pytorch \
LD_LIBRARY_PATH=/content/rfd1_env/lib:$LD_LIBRARY_PATH \
PYTHONPATH=/content/RFdiffusion \
/content/bin/micromamba run \
-p /content/rfd1_env \
python -c "import torch, dgl, rfdiffusion; print('RFdiffusion original import OK'); print('Torch:',torch.__version__); print('DGL:',dgl.__version__)"

RFdiffusion original import OK
Torch: 1.12.1+cu116
DGL: 1.0.2+cu116

In [18]:
#checkpoint exist or not

!find /content/RFdiffusion -type f \
  \( -name "*.pt" -o -name "*.pkl" \) \
  -print

/content/RFdiffusion/examples/target_folds/insulin_target_adj.pt
/content/RFdiffusion/examples/target_folds/insulin_target_ss.pt
/content/RFdiffusion/examples/tim_barrel_scaffold/6WVS_ss.pt
/content/RFdiffusion/examples/tim_barrel_scaffold/6WVS_adj.pt

In [19]:
!mkdir -p /content/RFdiffusion/models

In [20]:
!wget -O /content/RFdiffusion/models/Complex_base_ckpt.pt \
https://files.ipd.uw.edu/pub/RFdiffusion/6f5902ac237024bdd0c176cb93063dc4/Complex_base_ckpt.pt

--2026-08-24 11:37:09--  https://files.ipd.uw.edu/pub/RFdiffusion/6f5902ac237024bdd0c176cb93063dc4/Complex_base_ckpt.pt
Resolving files.ipd.uw.edu (files.ipd.uw.edu)... 128.95.160.134, 128.95.160.135, 2607:4000:406::160:134, ...
Connecting to files.ipd.uw.edu (files.ipd.uw.edu)|128.95.160.134|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2026-08-24 11:37:11 ERROR 404: Not Found.

In [21]:
!ls -lh /content/RFdiffusion/models/Complex_base_ckpt.pt

-rw-r--r-- 1 root root 0 Aug 24 11:37 /content/RFdiffusion/models/Complex_base_ckpt.pt

In [22]:
!test -f /content/RFdiffusion/models/Complex_base_ckpt.pt && echo "✅ Complex_base_ckpt.pt found"

✅ Complex_base_ckpt.pt found

In [23]:
PDB_FILE = "/content/6y5wB.pdb"

chains = {}

with open(PDB_FILE) as f:
    for line in f:
        if line.startswith("ATOM"):
            chain = line[21].strip() or "_"
            resi = int(line[22:26])

            if chain not in chains:
                chains[chain] = set()

            chains[chain].add(resi)

print("PDB:", PDB_FILE)

for chain, residues in chains.items():
    residues = sorted(residues)
    print(
        f"Chain {chain}: "
        f"{residues[0]}-{residues[-1]} "
        f"({len(residues)} residues)"
    )

PDB: /content/6y5wB.pdb
Chain B: 659-1069 (405 residues)

In [24]:
PDB_FILE = "/content/6y5wB.pdb"

# ===== RFdiffusion settings =====

CONTIGS = "B703-950/0 50-70"

HOTSPOTS = ["B739", "B766", "B900"]

NUM_DESIGNS = 5

OUTPUT_PREFIX = "/content/rfd1_outputs/design"

In [25]:
f"contigmap.contigs=[{CONTIGS}]"

'contigmap.contigs=[B703-950/0 50-70]'

In [26]:
!ls -lh /content/RFdiffusion/models/Complex_base_ckpt.pt
!stat -c "%s bytes" /content/RFdiffusion/models/Complex_base_ckpt.pt

-rw-r--r-- 1 root root 0 Aug 24 11:37 /content/RFdiffusion/models/Complex_base_ckpt.pt
0 bytes

In [27]:
!rm -f /content/RFdiffusion/models/Complex_base_ckpt.pt

!wget -O /content/RFdiffusion/models/Complex_base_ckpt.pt \
http://files.ipd.uw.edu/pub/RFdiffusion/e29311f6f1bf1af907f9ef9f44b8328b/Complex_base_ckpt.pt

--2026-08-24 11:37:12--  http://files.ipd.uw.edu/pub/RFdiffusion/e29311f6f1bf1af907f9ef9f44b8328b/Complex_base_ckpt.pt
Resolving files.ipd.uw.edu (files.ipd.uw.edu)... 128.95.160.134, 128.95.160.135, 2607:4000:406::160:134, ...
Connecting to files.ipd.uw.edu (files.ipd.uw.edu)|128.95.160.134|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 483619179 (461M) [application/octet-stream]
Saving to: ‘/content/RFdiffusion/models/Complex_base_ckpt.pt’

/content/RFdiffusio 100%[===================>] 461.21M  10.5MB/s    in 36s

2026-08-24 11:37:48 (12.7 MB/s) - ‘/content/RFdiffusion/models/Complex_base_ckpt.pt’ saved [483619179/483619179]

In [28]:
!ls -lh /content/RFdiffusion/models/Complex_base_ckpt.pt
!stat -c "Size = %s bytes" /content/RFdiffusion/models/Complex_base_ckpt.pt

-rw-r--r-- 1 root root 462M Mar 30  2023 /content/RFdiffusion/models/Complex_base_ckpt.pt
Size = 483619179 bytes

In [29]:
!LD_LIBRARY_PATH=/content/rfd1_env/lib:$LD_LIBRARY_PATH \
/content/bin/micromamba run -p /content/rfd1_env \
python -c "import torch; p='/content/RFdiffusion/models/Complex_base_ckpt.pt'; c=torch.load(p,map_location='cpu'); print('✅ Checkpoint load OK'); print(c.keys())"

✅ Checkpoint load OK
dict_keys(['model_state_dict', 'final_state_dict', 'config_dict'])

In [30]:
#RFdiffusion
import os
import subprocess

os.makedirs("/content/rfd1_outputs", exist_ok=True)

hotspots = ",".join(HOTSPOTS)

cmd = [
    "/content/bin/micromamba", "run",
    "-p", "/content/rfd1_env",
    "python",
    "/content/RFdiffusion/scripts/run_inference.py",

    f"inference.input_pdb={PDB_FILE}",
    f"inference.output_prefix={OUTPUT_PREFIX}",

    # บอก checkpoint ให้ชัดเจน
    "inference.ckpt_override_path=/content/RFdiffusion/models/Complex_base_ckpt.pt",

    f"contigmap.contigs=[{CONTIGS}]",
    f"ppi.hotspot_res=[{hotspots}]",
    f"inference.num_designs={NUM_DESIGNS}",
]

env = os.environ.copy()

env["DGLBACKEND"] = "pytorch"
env["LD_LIBRARY_PATH"] = (
    "/content/rfd1_env/lib:" +
    env.get("LD_LIBRARY_PATH", "")
)

env["PYTHONPATH"] = (
    "/content/RFdiffusion:" +
    env.get("PYTHONPATH", "")
)

env["HYDRA_FULL_ERROR"] = "1"

print("Running RFdiffusion...")
print("PDB       :", PDB_FILE)
print("CONTIGS   :", CONTIGS)
print("HOTSPOTS  :", HOTSPOTS)
print("DESIGNS   :", NUM_DESIGNS)
print("CHECKPOINT:", "/content/RFdiffusion/models/Complex_base_ckpt.pt")
print()

result = subprocess.run(
    cmd,
    env=env,
    text=True,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT
)

print(result.stdout)
print("\nReturn code:", result.returncode)

Running RFdiffusion...
PDB       : /content/6y5wB.pdb
CONTIGS   : B703-950/0 50-70
HOTSPOTS  : ['B739', 'B766', 'B900']
DESIGNS   : 5
CHECKPOINT: /content/RFdiffusion/models/Complex_base_ckpt.pt

[2026-08-24 11:37:53,967][__main__][INFO] - Found GPU with device_name Tesla T4. Will run RFdiffusion on Tesla T4
Reading models from /content/RFdiffusion/rfdiffusion/inference/../../models
WARNING: You're overriding the checkpoint path from the defaults. Check that the model you're providing can run with the inputs you're providing.
[2026-08-24 11:37:53,968][rfdiffusion.inference.model_runners][INFO] - Reading checkpoint from /content/RFdiffusion/models/Complex_base_ckpt.pt
This is inf_conf.ckpt_path
/content/RFdiffusion/models/Complex_base_ckpt.pt
Assembling -model, -diffuser and -preprocess configs from checkpoint
USING MODEL CONFIG: self._conf[model][n_extra_block] = 4
USING MODEL CONFIG: self._conf[model][n_main_block] = 32
USING MODEL CONFIG: self._conf[model][n_ref_block] = 4
USING MODEL CONFIG: self._conf[model][d_msa] = 256
USING MODEL CONFIG: self._conf[model][d_msa_full] = 64
USING MODEL CONFIG: self._conf[model][d_pair] = 128
USING MODEL CONFIG: self._conf[model][d_templ] = 64
USING MODEL CONFIG: self._conf[model][n_head_msa] = 8
USING MODEL CONFIG: self._conf[model][n_head_pair] = 4
USING MODEL CONFIG: self._conf[model][n_head_templ] = 4
USING MODEL CONFIG: self._conf[model][d_hidden] = 32
USING MODEL CONFIG: self._conf[model][d_hidden_templ] = 32
USING MODEL CONFIG: self._conf[model][p_drop] = 0.15
USING MODEL CONFIG: self._conf[model][SE3_param_full] = {'num_layers': 1, 'num_channels': 32, 'num_degrees': 2, 'n_heads': 4, 'div': 4, 'l0_in_features': 8, 'l0_out_features': 8, 'l1_in_features': 3, 'l1_out_features': 2, 'num_edge_features': 32}
USING MODEL CONFIG: self._conf[model][SE3_param_topk] = {'num_layers': 1, 'num_channels': 32, 'num_degrees': 2, 'n_heads': 4, 'div': 4, 'l0_in_features': 64, 'l0_out_features': 64, 'l1_in_features': 3, 'l1_out_features': 2, 'num_edge_features': 64}
USING MODEL CONFIG: self._conf[model][freeze_track_motif] = False
USING MODEL CONFIG: self._conf[model][use_motif_timestep] = True
USING MODEL CONFIG: self._conf[diffuser][T] = 50
USING MODEL CONFIG: self._conf[diffuser][b_0] = 0.01
USING MODEL CONFIG: self._conf[diffuser][b_T] = 0.07
USING MODEL CONFIG: self._conf[diffuser][schedule_type] = linear
USING MODEL CONFIG: self._conf[diffuser][so3_type] = igso3
USING MODEL CONFIG: self._conf[diffuser][crd_scale] = 0.25
USING MODEL CONFIG: self._conf[diffuser][so3_schedule_type] = linear
USING MODEL CONFIG: self._conf[diffuser][min_b] = 1.5
USING MODEL CONFIG: self._conf[diffuser][max_b] = 2.5
USING MODEL CONFIG: self._conf[diffuser][min_sigma] = 0.02
USING MODEL CONFIG: self._conf[diffuser][max_sigma] = 1.5
USING MODEL CONFIG: self._conf[preprocess][sidechain_input] = False
USING MODEL CONFIG: self._conf[preprocess][motif_sidechain_input] = True
USING MODEL CONFIG: self._conf[preprocess][d_t1d] = 24
USING MODEL CONFIG: self._conf[preprocess][d_t2d] = 44
USING MODEL CONFIG: self._conf[preprocess][prob_self_cond] = 0.5
USING MODEL CONFIG: self._conf[preprocess][str_self_cond] = True
USING MODEL CONFIG: self._conf[preprocess][predict_previous] = False
[2026-08-24 11:38:01,093][rfdiffusion.inference.model_runners][INFO] - Loading checkpoint.
[2026-08-24 11:38:07,068][rfdiffusion.diffusion][INFO] - Calculating IGSO3.
Successful diffuser __init__
[2026-08-24 11:38:32,361][__main__][INFO] - Making design /content/rfd1_outputs/design_0
[2026-08-24 11:38:32,408][rfdiffusion.inference.model_runners][INFO] - Using contig: ['B703-950/0 50-70']
With this beta schedule (linear schedule, beta_0 = 0.04, beta_T = 0.28), alpha_bar_T = 0.00013696048699785024
[2026-08-24 11:38:32,492][rfdiffusion.inference.model_runners][INFO] - Sequence init: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
/content/RFdiffusion/rfdiffusion/Embeddings.py:50: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  seqsep[:,cur_mask*(seqsep[0]>cur_ncyc//2)] -= cur_ncyc
/content/RFdiffusion/rfdiffusion/Embeddings.py:51: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  seqsep[:,cur_mask*(seqsep[0]<-cur_ncyc//2)] += cur_ncyc
/content/rfd1_env/lib/python3.9/site-packages/e3nn/o3/_spherical_harmonics.py:82: UserWarning: FALLBACK path has been taken inside: compileCudaFusionGroup. This is an indication that codegen Failed for some reason.
To debug try disable codegen fallback path via setting the env variable `export PYTORCH_NVFUSER_DISABLE=fallback`
To report the issue, try enable logging via setting the envvariable ` export PYTORCH_JIT_LOG_LEVEL=manager.cpp`
 (Triggered internally at  ../torch/csrc/jit/codegen/cuda/manager.cpp:237.)
  sh = _spherical_harmonics(self._lmax, x[..., 0], x[..., 1], x[..., 2])
[2026-08-24 11:38:41,739][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.11
[2026-08-24 11:38:41,754][rfdiffusion.inference.model_runners][INFO] - Timestep 50, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:38:46,386][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.11
[2026-08-24 11:38:46,389][rfdiffusion.inference.model_runners][INFO] - Timestep 49, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:38:50,962][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.12
[2026-08-24 11:38:50,966][rfdiffusion.inference.model_runners][INFO] - Timestep 48, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:38:55,570][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.11
[2026-08-24 11:38:55,575][rfdiffusion.inference.model_runners][INFO] - Timestep 47, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:39:00,291][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.12
[2026-08-24 11:39:00,295][rfdiffusion.inference.model_runners][INFO] - Timestep 46, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:39:04,962][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.12
[2026-08-24 11:39:04,965][rfdiffusion.inference.model_runners][INFO] - Timestep 45, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:39:09,671][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.11
[2026-08-24 11:39:09,676][rfdiffusion.inference.model_runners][INFO] - Timestep 44, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:39:14,428][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.12
[2026-08-24 11:39:14,431][rfdiffusion.inference.model_runners][INFO] - Timestep 43, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:39:19,147][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.11
[2026-08-24 11:39:19,150][rfdiffusion.inference.model_runners][INFO] - Timestep 42, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:39:23,930][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.12
[2026-08-24 11:39:23,935][rfdiffusion.inference.model_runners][INFO] - Timestep 41, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:39:28,767][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.12
[2026-08-24 11:39:28,770][rfdiffusion.inference.model_runners][INFO] - Timestep 40, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:39:33,573][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.12
[2026-08-24 11:39:33,577][rfdiffusion.inference.model_runners][INFO] - Timestep 39, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:39:38,449][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.12
[2026-08-24 11:39:38,452][rfdiffusion.inference.model_runners][INFO] - Timestep 38, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:39:43,317][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.12
[2026-08-24 11:39:43,321][rfdiffusion.inference.model_runners][INFO] - Timestep 37, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:39:48,229][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.12
[2026-08-24 11:39:48,233][rfdiffusion.inference.model_runners][INFO] - Timestep 36, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:39:53,236][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.12
[2026-08-24 11:39:53,240][rfdiffusion.inference.model_runners][INFO] - Timestep 35, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:39:58,211][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.12
[2026-08-24 11:39:58,214][rfdiffusion.inference.model_runners][INFO] - Timestep 34, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:40:03,247][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.13
[2026-08-24 11:40:03,252][rfdiffusion.inference.model_runners][INFO] - Timestep 33, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:40:08,290][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.12
[2026-08-24 11:40:08,294][rfdiffusion.inference.model_runners][INFO] - Timestep 32, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:40:13,269][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.13
[2026-08-24 11:40:13,272][rfdiffusion.inference.model_runners][INFO] - Timestep 31, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:40:18,242][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.13
[2026-08-24 11:40:18,246][rfdiffusion.inference.model_runners][INFO] - Timestep 30, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:40:23,164][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.13
[2026-08-24 11:40:23,167][rfdiffusion.inference.model_runners][INFO] - Timestep 29, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:40:28,098][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.13
[2026-08-24 11:40:28,103][rfdiffusion.inference.model_runners][INFO] - Timestep 28, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:40:33,050][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.13
[2026-08-24 11:40:33,053][rfdiffusion.inference.model_runners][INFO] - Timestep 27, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:40:37,940][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.13
[2026-08-24 11:40:37,944][rfdiffusion.inference.model_runners][INFO] - Timestep 26, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:40:42,863][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.13
[2026-08-24 11:40:42,867][rfdiffusion.inference.model_runners][INFO] - Timestep 25, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:40:47,750][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.13
[2026-08-24 11:40:47,754][rfdiffusion.inference.model_runners][INFO] - Timestep 24, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:40:52,638][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.13
[2026-08-24 11:40:52,643][rfdiffusion.inference.model_runners][INFO] - Timestep 23, input to next step: ------------------------------------------------------------------SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT
[2026-08-24 11:40:57,610][rfdiffusion.inference.utils][INFO] - Sampled motif RMSD: 0.13

In [31]:
#mpnn

In [32]:
%cd /content
!git clone https://github.com/dauparas/ProteinMPNN.git

/content
Cloning into 'ProteinMPNN'...
remote: Enumerating objects: 634, done.
remote: Counting objects: 100% (256/256), done.
remote: Compressing objects: 100% (124/124), done.
remote: Total 634 (delta 137), reused 132 (delta 132), pack-reused 378 (from 1)
Receiving objects: 100% (634/634), 119.90 MiB | 19.92 MiB/s, done.
Resolving deltas: 100% (290/290), done.

In [33]:
!/content/bin/micromamba run \
-p /content/rfd1_env \
python -c "import torch; print(torch.__version__)"

1.12.1+cu116

In [34]:
from pathlib import Path

for pdb in sorted(Path("/content/rfd1_outputs").glob("design_*.pdb")):
    chains = set()

    with open(pdb) as f:
        for line in f:
            if line.startswith("ATOM"):
                chains.add(line[21].strip())

    print(pdb.name, "chains:", sorted(chains))

design_0.pdb chains: ['A', 'B']
design_1.pdb chains: ['A', 'B']
design_2.pdb chains: ['A', 'B']
design_3.pdb chains: ['A', 'B']
design_4.pdb chains: ['A', 'B']

In [35]:
!/content/bin/micromamba run \
-p /content/rfd1_env \
python helper_scripts/assign_fixed_chains.py \
--input_path=/content/rfd1_outputs/parsed_pdbs.jsonl \
--output_path=/content/rfd1_outputs/assigned_pdbs.jsonl \
--chain_list "A"

python: can't open file '/content/helper_scripts/assign_fixed_chains.py': [Errno 2] No such file or directory

In [36]:
%cd /content

!git clone https://github.com/dauparas/ProteinMPNN.git

/content
fatal: destination path 'ProteinMPNN' already exists and is not an empty directory.

In [37]:
!ls /content/ProteinMPNN/helper_scripts

assign_fixed_chains.py		     make_tied_positions_dict.py
make_bias_AA.py			     other_tools
make_bias_per_res_dict.py	     parse_multiple_chains.out
make_fixed_positions_dict.py	     parse_multiple_chains.py
make_pos_neg_tied_positions_dict.py  parse_multiple_chains.sh
make_pssm_input_dict.py

In [38]:
from pathlib import Path

for pdb in sorted(Path("/content/rfd1_outputs").glob("design_*.pdb")):
    chains = {}

    with open(pdb) as f:
        for line in f:
            if line.startswith("ATOM"):
                chain = line[21].strip()
                resi = int(line[22:26])

                if chain not in chains:
                    chains[chain] = set()

                chains[chain].add(resi)

    print("\n", pdb.name)

    for chain, residues in chains.items():
        print(
            f"  Chain {chain}: "
            f"{min(residues)}-{max(residues)} "
            f"({len(residues)} residues)"
        )

 design_0.pdb
  Chain A: 1-66 (66 residues)
  Chain B: 703-950 (248 residues)

 design_1.pdb
  Chain A: 1-64 (64 residues)
  Chain B: 703-950 (248 residues)

 design_2.pdb
  Chain A: 1-60 (60 residues)
  Chain B: 703-950 (248 residues)

 design_3.pdb
  Chain A: 1-62 (62 residues)
  Chain B: 703-950 (248 residues)

 design_4.pdb
  Chain A: 1-60 (60 residues)
  Chain B: 703-950 (248 residues)

In [39]:
%cd /content/ProteinMPNN

!/content/bin/micromamba run \
-p /content/rfd1_env \
python helper_scripts/parse_multiple_chains.py \
--input_path=/content/rfd1_outputs \
--output_path=/content/rfd1_outputs/parsed_pdbs.jsonl

/content/ProteinMPNN

In [40]:
!/content/bin/micromamba run \
-p /content/rfd1_env \
python /content/ProteinMPNN/helper_scripts/assign_fixed_chains.py \
--input_path=/content/rfd1_outputs/parsed_pdbs.jsonl \
--output_path=/content/rfd1_outputs/assigned_pdbs.jsonl \
--chain_list "A"

In [41]:
%cd /content/ProteinMPNN

!/content/bin/micromamba run \
-p /content/rfd1_env \
python protein_mpnn_run.py \
--jsonl_path /content/rfd1_outputs/parsed_pdbs.jsonl \
--chain_id_jsonl /content/rfd1_outputs/assigned_pdbs.jsonl \
--out_folder /content/mpnn_outputs \
--num_seq_per_target 8 \
--sampling_temp "0.1" \
--seed 37 \
--batch_size 1

/content/ProteinMPNN
----------------------------------------
fixed_positions_jsonl is NOT loaded
----------------------------------------
pssm_jsonl is NOT loaded
----------------------------------------
omit_AA_jsonl is NOT loaded
----------------------------------------
bias_AA_jsonl is NOT loaded
----------------------------------------
tied_positions_jsonl is NOT loaded
----------------------------------------
bias by residue dictionary is not loaded, or not provided
----------------------------------------
discarded {'bad_chars': 0, 'too_long': 0, 'bad_seq_length': 0}
----------------------------------------
Number of edges: 48
Training noise level: 0.2A
Generating sequences for: design_1
8 sequences of length 312 generated in 8.6139 seconds
Generating sequences for: design_4
8 sequences of length 308 generated in 9.2754 seconds
Generating sequences for: design_0
8 sequences of length 314 generated in 9.4971 seconds
Generating sequences for: design_2
8 sequences of length 308 generated in 8.5223 seconds
Generating sequences for: design_3
8 sequences of length 310 generated in 9.2221 seconds

In [42]:
from pathlib import Path

seq_dir = Path("/content/mpnn_outputs/seqs")

files = sorted(seq_dir.glob("*.fa"))

print("Found", len(files), "FASTA files")

for fa in files:
    print("\n==============================")
    print(fa.name)
    print("==============================")
    print(fa.read_text())

Found 5 FASTA files

==============================
design_0.fa
==============================
>design_0, score=2.6287, global_score=1.9840, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>T=0.1, sample=1, score=1.2752, global_score=1.6973, seq_recovery=0.0000
SELLARLLALLSAAAAAAALAADPAAVAAAVAATAAAAAAAAALAAAAAAAAAALEALAALKAELE
>T=0.1, sample=2, score=1.2551, global_score=1.6890, seq_recovery=0.0000
SAALAAALAAASAAALAALLAAAPAVVAAAVAATLAAALAAQAAKAAAAAALAAALAEAAAAAALA
>T=0.1, sample=3, score=1.1422, global_score=1.6683, seq_recovery=0.0000
SLLASQLLALASAAALAAAVAADPAAVAALVAATRAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAA
>T=0.1, sample=4, score=1.2693, global_score=1.7183, seq_recovery=0.0000
SRALAEALAALSAAALAALAATNPALVAAAVAATAAAAAAAAAAAKALAALLAALAAAAEAAAAAA
>T=0.1, sample=5, score=1.0433, global_score=1.6411, seq_recovery=0.0000
SLAAAAALAAASAAALAAALAADPAAVAAAVAATAAAAAAAAAAAAAAAAAEAAAAAAAEAAAAAA
>T=0.1, sample=6, score=1.2855, global_score=1.7191, seq_recovery=0.0152
SSLLSELLRLLSALAGAALAALAPALVAAQVAATAAAAAAAEAAKKAAAAAAAALAEAAAAAAALA
>T=0.1, sample=7, score=1.2686, global_score=1.7094, seq_recovery=0.0000
SAAAAAAAAAASAAALAALAATDPAAVAAAVAATAAAAAAEAKKKAEEAAAKKEKEAKKKEEEEKK
>T=0.1, sample=8, score=1.3074, global_score=1.7219, seq_recovery=0.0000
SEALAAALAAASAAALAAALAADPAAVAAAVAATKAKAEAEKAAKAAKEAEEAKKKKELEEKLKKL


==============================
design_1.fa
==============================
>design_1, score=2.4615, global_score=1.9719, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>T=0.1, sample=1, score=1.2230, global_score=1.6971, seq_recovery=0.0156
SEAARRAAEEAAAAAAAAAAAAAAAAAAAAAALGAALAAEAAAAAAAAIARAAAAAAAAAAAAA
>T=0.1, sample=2, score=1.2082, global_score=1.7163, seq_recovery=0.0156
SLAELLEEAAEAAAAAAAAAAAAAAAAAAAAARGAALAAAAAAAAAAARARAAAAAAAAAAAAA
>T=0.1, sample=3, score=1.2323, global_score=1.7169, seq_recovery=0.0156
SLEDLLKELEEAAAAAAAAAAAAAARAAAAAALGAALAAAAAAAAAAAVARAAAAAAAAAAAAA
>T=0.1, sample=4, score=1.3735, global_score=1.7321, seq_recovery=0.0156
SELEKLAEEAAAAEAAAKAAEEEAARRAAAAALGAALAAAAAAAAAAARERAAAAAAAAAAALA
>T=0.1, sample=5, score=1.2358, global_score=1.7199, seq_recovery=0.0156
SLEEELEKARKAAEAAAKAAAAAAAAAAAAAALGAALAAAAAAAAAAARARAAAEAAAAAAAAA
>T=0.1, sample=6, score=1.2214, global_score=1.7005, seq_recovery=0.0156
SLADLLAAAAAAAAAAAARAAAEAARRAAAAAVGAALAAAAAAAAAAAIARAAAAAAAAAAAAA
>T=0.1, sample=7, score=1.1530, global_score=1.7063, seq_recovery=0.0156
SLEAAEALAAAAAAAAAAAAAAAAAAAAAAAARGAALAAAAAAAAAAAVARAAAEAAAAAAAAE
>T=0.1, sample=8, score=1.1901, global_score=1.6994, seq_recovery=0.0156
SLAEQVAEALAAAAAAAAAAAAQAAADAAAAARGAADAAAAAAAAAAAIARAAAAAAAAAAAAA


==============================
design_2.fa
==============================
>design_2, score=2.2764, global_score=1.9144, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>T=0.1, sample=1, score=1.3109, global_score=1.7069, seq_recovery=0.0000
AEAAAAEEAAKAAAEAALAAALAALAAAAAAALRAAAQAALAAAAAAAAAAAAAAAAAAA
>T=0.1, sample=2, score=1.3353, global_score=1.7255, seq_recovery=0.0000
EKEEEEEEEEEEEEEEEEEEEELEEEEEEEEEEEEEEREALAAAVAAALAAAAAAALAAA
>T=0.1, sample=3, score=1.4681, global_score=1.7504, seq_recovery=0.0000
AEEEEEEEERRREEEEEELAEELAALAAEAAALAAAARAALAAAAAAAAAAAAAAEAAKR
>T=0.1, sample=4, score=1.3758, global_score=1.7315, seq_recovery=0.0000
AEEAEAEAARRAAEAAAAAAEALAALAAAAAALAALLRAAAAAAAAAAAAAAAAERAAAA
>T=0.1, sample=5, score=1.2240, global_score=1.7296, seq_recovery=0.0000
AEAEAAAAAAAAAAAAAAAAALAAALAAAAAAAAAARRAALAAAVAAAAAAALASALAAL
>T=0.1, sample=6, score=1.2368, global_score=1.6928, seq_recovery=0.0000
AAAEAAAAALEAAAAAAAAAAAAAALAAAAAALAAALRAALAAAVAAALAAAAAAAAAAL
>T=0.1, sample=7, score=1.4576, global_score=1.7656, seq_recovery=0.0000
EEEERERREREERERAEREAEEAARALAAAAAEAAARRAALAAAVAAAEAARAAAEALAA
>T=0.1, sample=8, score=1.2685, global_score=1.7127, seq_recovery=0.0000
AEAEAAEAARAAEEAALAAAAAAAAAAAAAAALAAQARAALAAAAAAAAAAAAAAAAAAA


==============================
design_3.fa
==============================
>design_3, score=2.3757, global_score=1.9208, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>T=0.1, sample=1, score=1.3167, global_score=1.7230, seq_recovery=0.0161
AAAAAAAAALAAALAAAAAALAPLVRALGAVNYALSLAETAALLAALAAAAAAAAAALEAAA
>T=0.1, sample=2, score=1.3372, global_score=1.7122, seq_recovery=0.0161
AALAALAAALAALLAAALASLAPLIAALGAVNYAASAAETAALAAEAAAAAAAEAAAAAAAA
>T=0.1, sample=3, score=1.3302, global_score=1.7377, seq_recovery=0.0161
AAEEAAAAAAAAAAAAAAAALAPLVRALGAVNYALSSAVTAALAAAAAAAAAAAAEEAALAA
>T=0.1, sample=4, score=1.2962, global_score=1.7060, seq_recovery=0.0161
SEEAALAALAAALAAAAAAALAPLVLALGAVNYAAAAAETAALAAAAAAAAAAAAAAEALAA
>T=0.1, sample=5, score=1.4233, global_score=1.7643, seq_recovery=0.0161
SLLAALAAALAALLRALLDALRPLVEALGAANAAASAAVTAALAAAAAAALAEAAAAEAARR
>T=0.1, sample=6, score=1.2386, global_score=1.7357, seq_recovery=0.0161
ATLAALAAALAAALRALAAALAPLVLALGAVNAAAAAAVTAAAAAAAAAAAAAAAAAAAAAA
>T=0.1, sample=7, score=1.3252, global_score=1.7352, seq_recovery=0.0161
SALSALLAALLALLLAALAALSPLIAALGAVNAAAAAAVTAAAAAAAAAAAAAAAEAAAAAA
>T=0.1, sample=8, score=1.0951, global_score=1.6829, seq_recovery=0.0161
AAAAAAAAAAAAAAAAAAAALAPAVAAAGAAAAAAAAAETAAAAAAAAAAAAAAAAAAAAAA


==============================
design_4.fa
==============================
>design_4, score=2.3746, global_score=1.9191, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>T=0.1, sample=1, score=1.2988, global_score=1.7258, seq_recovery=0.0167
DAAAALAAAAAAAAAAAAAAAAAAAAAAGAALRAAIAAALAAAEEAAAALERLRAELEAL
>T=0.1, sample=2, score=1.1240, global_score=1.6880, seq_recovery=0.0167
DAAAAAAAAAAAAAAAAAAAARAASAAAGAALAAAQAAAAAAAAAAAAALAAAALAAALA
>T=0.1, sample=3, score=1.1998, global_score=1.7045, seq_recovery=0.0167
DLAALLAALAAAAAAAAAAAAAAASAAAGAALRAAQTAAAAAAAAAAAAAAALAAAALAA
>T=0.1, sample=4, score=1.1408, global_score=1.6963, seq_recovery=0.0167
SLEEALAAAAAAAAAAAAAAAAAASAAAGAALAAAQAAAAAAAAAAAAAAAALAALEAAA
>T=0.1, sample=5, score=1.1433, global_score=1.6996, seq_recovery=0.0167
SLEELLRAAAAAAAAAAAAAARAASAAAGAALRAAIAAAAAAAAAAAAAAAAAAAALAAL
>T=0.1, sample=6, score=1.0310, global_score=1.6587, seq_recovery=0.0167
SLAELLAAAAAAAAAAAAAAAAAAAAAAGAALAAAQAAAAAAAAAAAAAAAAAAAAAAAA
>T=0.1, sample=7, score=1.1953, global_score=1.7149, seq_recovery=0.0167
SLAEQLEKLAAEAAAAAAAAAAAASAAAGAALAAAQAAAAAAAAALAAAAAAALAAAAAA
>T=0.1, sample=8, score=1.1624, global_score=1.6777, seq_recovery=0.0167
SAEALREAEAAAAAAAAAAAAAAASAAAGAALAAAQAAAAAAAAAAAAAAAAAAAKAAAA

In [43]:
from pathlib import Path

search_dirs = [
    Path("/content/rfd1_outputs"),
    Path("/content/ProteinMPNN"),
]

fasta_files = []

for d in search_dirs:
    if d.exists():
        fasta_files.extend(d.rglob("design_*.fa"))
        fasta_files.extend(d.rglob("design_*.fasta"))

fasta_files = sorted(set(fasta_files))

print(f"Found {len(fasta_files)} FASTA files\n")

for f in fasta_files:
    print(f)

Found 0 FASTA files

In [44]:
from pathlib import Path

fasta_files = []

for ext in ("*.fa", "*.fasta", "*.faa"):
    fasta_files.extend(Path("/content").rglob(ext))

fasta_files = sorted(set(fasta_files))

print(f"Found {len(fasta_files)} FASTA-like files\n")

for f in fasta_files:
    print(f)

Found 23 FASTA-like files

/content/ProteinMPNN/outputs/example_1_outputs/seqs/5L33.fa
/content/ProteinMPNN/outputs/example_1_outputs/seqs/6MRR.fa
/content/ProteinMPNN/outputs/example_2_outputs/seqs/3HTN.fa
/content/ProteinMPNN/outputs/example_2_outputs/seqs/4YOW.fa
/content/ProteinMPNN/outputs/example_3_outputs/seqs/3HTN.fa
/content/ProteinMPNN/outputs/example_4_non_fixed_outputs/seqs/3HTN.fa
/content/ProteinMPNN/outputs/example_4_non_fixed_outputs/seqs/4YOW.fa
/content/ProteinMPNN/outputs/example_4_outputs/seqs/3HTN.fa
/content/ProteinMPNN/outputs/example_4_outputs/seqs/4YOW.fa
/content/ProteinMPNN/outputs/example_5_outputs/seqs/3HTN.fa
/content/ProteinMPNN/outputs/example_5_outputs/seqs/4YOW.fa
/content/ProteinMPNN/outputs/example_6_outputs/seqs/4GYT.fa
/content/ProteinMPNN/outputs/example_6_outputs/seqs/6EHB.fa
/content/ProteinMPNN/outputs/example_8_outputs/seqs/5L33.fa
/content/ProteinMPNN/outputs/example_8_outputs/seqs/6MRR.fa
/content/ProteinMPNN/outputs/example_pssm_outputs/seqs/3HTN.fa
/content/ProteinMPNN/outputs/example_pssm_outputs/seqs/4YOW.fa
/content/ProteinMPNN/outputs/training_test_output/seqs/5L33.fa
/content/mpnn_outputs/seqs/design_0.fa
/content/mpnn_outputs/seqs/design_1.fa
/content/mpnn_outputs/seqs/design_2.fa
/content/mpnn_outputs/seqs/design_3.fa
/content/mpnn_outputs/seqs/design_4.fa

In [45]:
from pathlib import Path

SEQ_DIR = Path("/content/mpnn_outputs/seqs")

for fa in sorted(SEQ_DIR.glob("design_*.fa")):
    print("\n" + "="*80)
    print(fa.name)
    print("="*80)

    with open(fa) as f:
        print(f.read())

================================================================================
design_0.fa
================================================================================
>design_0, score=2.6287, global_score=1.9840, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>T=0.1, sample=1, score=1.2752, global_score=1.6973, seq_recovery=0.0000
SELLARLLALLSAAAAAAALAADPAAVAAAVAATAAAAAAAAALAAAAAAAAAALEALAALKAELE
>T=0.1, sample=2, score=1.2551, global_score=1.6890, seq_recovery=0.0000
SAALAAALAAASAAALAALLAAAPAVVAAAVAATLAAALAAQAAKAAAAAALAAALAEAAAAAALA
>T=0.1, sample=3, score=1.1422, global_score=1.6683, seq_recovery=0.0000
SLLASQLLALASAAALAAAVAADPAAVAALVAATRAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAA
>T=0.1, sample=4, score=1.2693, global_score=1.7183, seq_recovery=0.0000
SRALAEALAALSAAALAALAATNPALVAAAVAATAAAAAAAAAAAKALAALLAALAAAAEAAAAAA
>T=0.1, sample=5, score=1.0433, global_score=1.6411, seq_recovery=0.0000
SLAAAAALAAASAAALAAALAADPAAVAAAVAATAAAAAAAAAAAAAAAAAEAAAAAAAEAAAAAA
>T=0.1, sample=6, score=1.2855, global_score=1.7191, seq_recovery=0.0152
SSLLSELLRLLSALAGAALAALAPALVAAQVAATAAAAAAAEAAKKAAAAAAAALAEAAAAAAALA
>T=0.1, sample=7, score=1.2686, global_score=1.7094, seq_recovery=0.0000
SAAAAAAAAAASAAALAALAATDPAAVAAAVAATAAAAAAEAKKKAEEAAAKKEKEAKKKEEEEKK
>T=0.1, sample=8, score=1.3074, global_score=1.7219, seq_recovery=0.0000
SEALAAALAAASAAALAAALAADPAAVAAAVAATKAKAEAEKAAKAAKEAEEAKKKKELEEKLKKL


================================================================================
design_1.fa
================================================================================
>design_1, score=2.4615, global_score=1.9719, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>T=0.1, sample=1, score=1.2230, global_score=1.6971, seq_recovery=0.0156
SEAARRAAEEAAAAAAAAAAAAAAAAAAAAAALGAALAAEAAAAAAAAIARAAAAAAAAAAAAA
>T=0.1, sample=2, score=1.2082, global_score=1.7163, seq_recovery=0.0156
SLAELLEEAAEAAAAAAAAAAAAAAAAAAAAARGAALAAAAAAAAAAARARAAAAAAAAAAAAA
>T=0.1, sample=3, score=1.2323, global_score=1.7169, seq_recovery=0.0156
SLEDLLKELEEAAAAAAAAAAAAAARAAAAAALGAALAAAAAAAAAAAVARAAAAAAAAAAAAA
>T=0.1, sample=4, score=1.3735, global_score=1.7321, seq_recovery=0.0156
SELEKLAEEAAAAEAAAKAAEEEAARRAAAAALGAALAAAAAAAAAAARERAAAAAAAAAAALA
>T=0.1, sample=5, score=1.2358, global_score=1.7199, seq_recovery=0.0156
SLEEELEKARKAAEAAAKAAAAAAAAAAAAAALGAALAAAAAAAAAAARARAAAEAAAAAAAAA
>T=0.1, sample=6, score=1.2214, global_score=1.7005, seq_recovery=0.0156
SLADLLAAAAAAAAAAAARAAAEAARRAAAAAVGAALAAAAAAAAAAAIARAAAAAAAAAAAAA
>T=0.1, sample=7, score=1.1530, global_score=1.7063, seq_recovery=0.0156
SLEAAEALAAAAAAAAAAAAAAAAAAAAAAAARGAALAAAAAAAAAAAVARAAAEAAAAAAAAE
>T=0.1, sample=8, score=1.1901, global_score=1.6994, seq_recovery=0.0156
SLAEQVAEALAAAAAAAAAAAAQAAADAAAAARGAADAAAAAAAAAAAIARAAAAAAAAAAAAA


================================================================================
design_2.fa
================================================================================
>design_2, score=2.2764, global_score=1.9144, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>T=0.1, sample=1, score=1.3109, global_score=1.7069, seq_recovery=0.0000
AEAAAAEEAAKAAAEAALAAALAALAAAAAAALRAAAQAALAAAAAAAAAAAAAAAAAAA
>T=0.1, sample=2, score=1.3353, global_score=1.7255, seq_recovery=0.0000
EKEEEEEEEEEEEEEEEEEEEELEEEEEEEEEEEEEEREALAAAVAAALAAAAAAALAAA
>T=0.1, sample=3, score=1.4681, global_score=1.7504, seq_recovery=0.0000
AEEEEEEEERRREEEEEELAEELAALAAEAAALAAAARAALAAAAAAAAAAAAAAEAAKR
>T=0.1, sample=4, score=1.3758, global_score=1.7315, seq_recovery=0.0000
AEEAEAEAARRAAEAAAAAAEALAALAAAAAALAALLRAAAAAAAAAAAAAAAAERAAAA
>T=0.1, sample=5, score=1.2240, global_score=1.7296, seq_recovery=0.0000
AEAEAAAAAAAAAAAAAAAAALAAALAAAAAAAAAARRAALAAAVAAAAAAALASALAAL
>T=0.1, sample=6, score=1.2368, global_score=1.6928, seq_recovery=0.0000
AAAEAAAAALEAAAAAAAAAAAAAALAAAAAALAAALRAALAAAVAAALAAAAAAAAAAL
>T=0.1, sample=7, score=1.4576, global_score=1.7656, seq_recovery=0.0000
EEEERERREREERERAEREAEEAARALAAAAAEAAARRAALAAAVAAAEAARAAAEALAA
>T=0.1, sample=8, score=1.2685, global_score=1.7127, seq_recovery=0.0000
AEAEAAEAARAAEEAALAAAAAAAAAAAAAAALAAQARAALAAAAAAAAAAAAAAAAAAA


================================================================================
design_3.fa
================================================================================
>design_3, score=2.3757, global_score=1.9208, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>T=0.1, sample=1, score=1.3167, global_score=1.7230, seq_recovery=0.0161
AAAAAAAAALAAALAAAAAALAPLVRALGAVNYALSLAETAALLAALAAAAAAAAAALEAAA
>T=0.1, sample=2, score=1.3372, global_score=1.7122, seq_recovery=0.0161
AALAALAAALAALLAAALASLAPLIAALGAVNYAASAAETAALAAEAAAAAAAEAAAAAAAA
>T=0.1, sample=3, score=1.3302, global_score=1.7377, seq_recovery=0.0161
AAEEAAAAAAAAAAAAAAAALAPLVRALGAVNYALSSAVTAALAAAAAAAAAAAAEEAALAA
>T=0.1, sample=4, score=1.2962, global_score=1.7060, seq_recovery=0.0161
SEEAALAALAAALAAAAAAALAPLVLALGAVNYAAAAAETAALAAAAAAAAAAAAAAEALAA
>T=0.1, sample=5, score=1.4233, global_score=1.7643, seq_recovery=0.0161
SLLAALAAALAALLRALLDALRPLVEALGAANAAASAAVTAALAAAAAAALAEAAAAEAARR
>T=0.1, sample=6, score=1.2386, global_score=1.7357, seq_recovery=0.0161
ATLAALAAALAAALRALAAALAPLVLALGAVNAAAAAAVTAAAAAAAAAAAAAAAAAAAAAA
>T=0.1, sample=7, score=1.3252, global_score=1.7352, seq_recovery=0.0161
SALSALLAALLALLLAALAALSPLIAALGAVNAAAAAAVTAAAAAAAAAAAAAAAEAAAAAA
>T=0.1, sample=8, score=1.0951, global_score=1.6829, seq_recovery=0.0161
AAAAAAAAAAAAAAAAAAAALAPAVAAAGAAAAAAAAAETAAAAAAAAAAAAAAAAAAAAAA


================================================================================
design_4.fa
================================================================================
>design_4, score=2.3746, global_score=1.9191, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
>T=0.1, sample=1, score=1.2988, global_score=1.7258, seq_recovery=0.0167
DAAAALAAAAAAAAAAAAAAAAAAAAAAGAALRAAIAAALAAAEEAAAALERLRAELEAL
>T=0.1, sample=2, score=1.1240, global_score=1.6880, seq_recovery=0.0167
DAAAAAAAAAAAAAAAAAAAARAASAAAGAALAAAQAAAAAAAAAAAAALAAAALAAALA
>T=0.1, sample=3, score=1.1998, global_score=1.7045, seq_recovery=0.0167
DLAALLAALAAAAAAAAAAAAAAASAAAGAALRAAQTAAAAAAAAAAAAAAALAAAALAA
>T=0.1, sample=4, score=1.1408, global_score=1.6963, seq_recovery=0.0167
SLEEALAAAAAAAAAAAAAAAAAASAAAGAALAAAQAAAAAAAAAAAAAAAALAALEAAA
>T=0.1, sample=5, score=1.1433, global_score=1.6996, seq_recovery=0.0167
SLEELLRAAAAAAAAAAAAAARAASAAAGAALRAAIAAAAAAAAAAAAAAAAAAAALAAL
>T=0.1, sample=6, score=1.0310, global_score=1.6587, seq_recovery=0.0167
SLAELLAAAAAAAAAAAAAAAAAAAAAAGAALAAAQAAAAAAAAAAAAAAAAAAAAAAAA
>T=0.1, sample=7, score=1.1953, global_score=1.7149, seq_recovery=0.0167
SLAEQLEKLAAEAAAAAAAAAAAASAAAGAALAAAQAAAAAAAAALAAAAAAALAAAAAA
>T=0.1, sample=8, score=1.1624, global_score=1.6777, seq_recovery=0.0167
SAEALREAEAAAAAAAAAAAAAAASAAAGAALAAAQAAAAAAAAAAAAAAAAAAAKAAAA

In [46]:
from pathlib import Path

SEQ_DIR = Path("/content/mpnn_outputs/seqs")

for fa in sorted(SEQ_DIR.glob("design_*.fa")):

    print("\n" + "="*70)
    print(f" {fa.name}")
    print("="*70)

    with open(fa) as f:
        lines = [x.strip() for x in f if x.strip()]

    for line in lines:
        if line.startswith(">"):
            print("\n", line)
        else:
            parts = line.split("/")

            print("Number of chains:", len(parts))

            for i, seq in enumerate(parts):
                print(
                    f"  part {i+1}: "
                    f"length={len(seq)}  "
                    f"first20={seq[:20]}..."
                )

======================================================================
 design_0.fa
======================================================================

 >design_0, score=2.6287, global_score=1.9840, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
Number of chains: 1
  part 1: length=66  first20=GGGGGGGGGGGGGGGGGGGG...

 >T=0.1, sample=1, score=1.2752, global_score=1.6973, seq_recovery=0.0000
Number of chains: 1
  part 1: length=66  first20=SELLARLLALLSAAAAAAAL...

 >T=0.1, sample=2, score=1.2551, global_score=1.6890, seq_recovery=0.0000
Number of chains: 1
  part 1: length=66  first20=SAALAAALAAASAAALAALL...

 >T=0.1, sample=3, score=1.1422, global_score=1.6683, seq_recovery=0.0000
Number of chains: 1
  part 1: length=66  first20=SLLASQLLALASAAALAAAV...

 >T=0.1, sample=4, score=1.2693, global_score=1.7183, seq_recovery=0.0000
Number of chains: 1
  part 1: length=66  first20=SRALAEALAALSAAALAALA...

 >T=0.1, sample=5, score=1.0433, global_score=1.6411, seq_recovery=0.0000
Number of chains: 1
  part 1: length=66  first20=SLAAAAALAAASAAALAAAL...

 >T=0.1, sample=6, score=1.2855, global_score=1.7191, seq_recovery=0.0152
Number of chains: 1
  part 1: length=66  first20=SSLLSELLRLLSALAGAALA...

 >T=0.1, sample=7, score=1.2686, global_score=1.7094, seq_recovery=0.0000
Number of chains: 1
  part 1: length=66  first20=SAAAAAAAAAASAAALAALA...

 >T=0.1, sample=8, score=1.3074, global_score=1.7219, seq_recovery=0.0000
Number of chains: 1
  part 1: length=66  first20=SEALAAALAAASAAALAAAL...

======================================================================
 design_1.fa
======================================================================

 >design_1, score=2.4615, global_score=1.9719, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
Number of chains: 1
  part 1: length=64  first20=GGGGGGGGGGGGGGGGGGGG...

 >T=0.1, sample=1, score=1.2230, global_score=1.6971, seq_recovery=0.0156
Number of chains: 1
  part 1: length=64  first20=SEAARRAAEEAAAAAAAAAA...

 >T=0.1, sample=2, score=1.2082, global_score=1.7163, seq_recovery=0.0156
Number of chains: 1
  part 1: length=64  first20=SLAELLEEAAEAAAAAAAAA...

 >T=0.1, sample=3, score=1.2323, global_score=1.7169, seq_recovery=0.0156
Number of chains: 1
  part 1: length=64  first20=SLEDLLKELEEAAAAAAAAA...

 >T=0.1, sample=4, score=1.3735, global_score=1.7321, seq_recovery=0.0156
Number of chains: 1
  part 1: length=64  first20=SELEKLAEEAAAAEAAAKAA...

 >T=0.1, sample=5, score=1.2358, global_score=1.7199, seq_recovery=0.0156
Number of chains: 1
  part 1: length=64  first20=SLEEELEKARKAAEAAAKAA...

 >T=0.1, sample=6, score=1.2214, global_score=1.7005, seq_recovery=0.0156
Number of chains: 1
  part 1: length=64  first20=SLADLLAAAAAAAAAAAARA...

 >T=0.1, sample=7, score=1.1530, global_score=1.7063, seq_recovery=0.0156
Number of chains: 1
  part 1: length=64  first20=SLEAAEALAAAAAAAAAAAA...

 >T=0.1, sample=8, score=1.1901, global_score=1.6994, seq_recovery=0.0156
Number of chains: 1
  part 1: length=64  first20=SLAEQVAEALAAAAAAAAAA...

======================================================================
 design_2.fa
======================================================================

 >design_2, score=2.2764, global_score=1.9144, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
Number of chains: 1
  part 1: length=60  first20=GGGGGGGGGGGGGGGGGGGG...

 >T=0.1, sample=1, score=1.3109, global_score=1.7069, seq_recovery=0.0000
Number of chains: 1
  part 1: length=60  first20=AEAAAAEEAAKAAAEAALAA...

 >T=0.1, sample=2, score=1.3353, global_score=1.7255, seq_recovery=0.0000
Number of chains: 1
  part 1: length=60  first20=EKEEEEEEEEEEEEEEEEEE...

 >T=0.1, sample=3, score=1.4681, global_score=1.7504, seq_recovery=0.0000
Number of chains: 1
  part 1: length=60  first20=AEEEEEEEERRREEEEEELA...

 >T=0.1, sample=4, score=1.3758, global_score=1.7315, seq_recovery=0.0000
Number of chains: 1
  part 1: length=60  first20=AEEAEAEAARRAAEAAAAAA...

 >T=0.1, sample=5, score=1.2240, global_score=1.7296, seq_recovery=0.0000
Number of chains: 1
  part 1: length=60  first20=AEAEAAAAAAAAAAAAAAAA...

 >T=0.1, sample=6, score=1.2368, global_score=1.6928, seq_recovery=0.0000
Number of chains: 1
  part 1: length=60  first20=AAAEAAAAALEAAAAAAAAA...

 >T=0.1, sample=7, score=1.4576, global_score=1.7656, seq_recovery=0.0000
Number of chains: 1
  part 1: length=60  first20=EEEERERREREERERAEREA...

 >T=0.1, sample=8, score=1.2685, global_score=1.7127, seq_recovery=0.0000
Number of chains: 1
  part 1: length=60  first20=AEAEAAEAARAAEEAALAAA...

======================================================================
 design_3.fa
======================================================================

 >design_3, score=2.3757, global_score=1.9208, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
Number of chains: 1
  part 1: length=62  first20=GGGGGGGGGGGGGGGGGGGG...

 >T=0.1, sample=1, score=1.3167, global_score=1.7230, seq_recovery=0.0161
Number of chains: 1
  part 1: length=62  first20=AAAAAAAAALAAALAAAAAA...

 >T=0.1, sample=2, score=1.3372, global_score=1.7122, seq_recovery=0.0161
Number of chains: 1
  part 1: length=62  first20=AALAALAAALAALLAAALAS...

 >T=0.1, sample=3, score=1.3302, global_score=1.7377, seq_recovery=0.0161
Number of chains: 1
  part 1: length=62  first20=AAEEAAAAAAAAAAAAAAAA...

 >T=0.1, sample=4, score=1.2962, global_score=1.7060, seq_recovery=0.0161
Number of chains: 1
  part 1: length=62  first20=SEEAALAALAAALAAAAAAA...

 >T=0.1, sample=5, score=1.4233, global_score=1.7643, seq_recovery=0.0161
Number of chains: 1
  part 1: length=62  first20=SLLAALAAALAALLRALLDA...

 >T=0.1, sample=6, score=1.2386, global_score=1.7357, seq_recovery=0.0161
Number of chains: 1
  part 1: length=62  first20=ATLAALAAALAAALRALAAA...

 >T=0.1, sample=7, score=1.3252, global_score=1.7352, seq_recovery=0.0161
Number of chains: 1
  part 1: length=62  first20=SALSALLAALLALLLAALAA...

 >T=0.1, sample=8, score=1.0951, global_score=1.6829, seq_recovery=0.0161
Number of chains: 1
  part 1: length=62  first20=AAAAAAAAAAAAAAAAAAAA...

======================================================================
 design_4.fa
======================================================================

 >design_4, score=2.3746, global_score=1.9191, fixed_chains=['B'], designed_chains=['A'], model_name=v_48_020, git_hash=8907e6671bfbfc92303b5f79c4b5e6ce47cdef57, seed=37
Number of chains: 1
  part 1: length=60  first20=GGGGGGGGGGGGGGGGGGGG...

 >T=0.1, sample=1, score=1.2988, global_score=1.7258, seq_recovery=0.0167
Number of chains: 1
  part 1: length=60  first20=DAAAALAAAAAAAAAAAAAA...

 >T=0.1, sample=2, score=1.1240, global_score=1.6880, seq_recovery=0.0167
Number of chains: 1
  part 1: length=60  first20=DAAAAAAAAAAAAAAAAAAA...

 >T=0.1, sample=3, score=1.1998, global_score=1.7045, seq_recovery=0.0167
Number of chains: 1
  part 1: length=60  first20=DLAALLAALAAAAAAAAAAA...

 >T=0.1, sample=4, score=1.1408, global_score=1.6963, seq_recovery=0.0167
Number of chains: 1
  part 1: length=60  first20=SLEEALAAAAAAAAAAAAAA...

 >T=0.1, sample=5, score=1.1433, global_score=1.6996, seq_recovery=0.0167
Number of chains: 1
  part 1: length=60  first20=SLEELLRAAAAAAAAAAAAA...

 >T=0.1, sample=6, score=1.0310, global_score=1.6587, seq_recovery=0.0167
Number of chains: 1
  part 1: length=60  first20=SLAELLAAAAAAAAAAAAAA...

 >T=0.1, sample=7, score=1.1953, global_score=1.7149, seq_recovery=0.0167
Number of chains: 1
  part 1: length=60  first20=SLAEQLEKLAAEAAAAAAAA...

 >T=0.1, sample=8, score=1.1624, global_score=1.6777, seq_recovery=0.0167
Number of chains: 1
  part 1: length=60  first20=SAEALREAEAAAAAAAAAAA...

In [47]:
from pathlib import Path

PDB_FILE = "/content/rfd1_outputs/design_0.pdb"

three_to_one = {
    "ALA":"A","ARG":"R","ASN":"N","ASP":"D","CYS":"C",
    "GLN":"Q","GLU":"E","GLY":"G","HIS":"H","ILE":"I",
    "LEU":"L","LYS":"K","MET":"M","PHE":"F","PRO":"P",
    "SER":"S","THR":"T","TRP":"W","TYR":"Y","VAL":"V"
}

residues = {}

with open(PDB_FILE) as f:
    for line in f:
        if line.startswith("ATOM") and line[21].strip() == "B":
            resi = (int(line[22:26]), line[26])
            resn = line[17:20].strip()
            residues[resi] = resn

TARGET_SEQ = "".join(
    three_to_one.get(residues[r], "X")
    for r in sorted(residues)
)

print("Target length:", len(TARGET_SEQ))
print(TARGET_SEQ)

Target length: 248
SIPFHFQMEKQVIHAEIQPLGHWMDATFNIKTAFHCYGACQKYSYPWQTSKCFFEKDYQYETGWGCNPGDCPGVGTGCTACGVYLDKLKSVGKAYKIISLKYTRKVCIQLGTEQTCKHIDANDCLVTPSVKVCIVGTVSKLQPSDTLLFLGPLEQGGIILKQWCTTSCAFGDPGDIMSTPSGMRCPEHTGSFRKICGFATTPVCEYQGNTISGYKRMMATKDSFQSFNLTEPHITTNKLEWIDPDGNT

In [48]:
import re
from pathlib import Path

SEQ_DIR = Path("/content/mpnn_outputs/seqs")

best_sequences = {}

for fa in sorted(SEQ_DIR.glob("design_*.fa")):
    lines = [x.strip() for x in fa.read_text().splitlines() if x.strip()]

    candidates = []

    for i in range(0, len(lines), 2):
        header = lines[i]
        seq = lines[i+1]

        # ข้าม polyG/native sequence บรรทัดแรก
        if "sample=" not in header:
            continue

        score = float(re.search(r"score=([0-9.]+)", header).group(1))
        sample = int(re.search(r"sample=(\d+)", header).group(1))

        candidates.append((score, sample, seq))

    score, sample, seq = min(candidates, key=lambda x: x[0])

    best_sequences[fa.stem] = {
        "sample": sample,
        "score": score,
        "binder": seq
    }

    print(
        fa.stem,
        "sample =", sample,
        "score =", score,
        "binder length =", len(seq)
    )

design_0 sample = 5 score = 1.0433 binder length = 66
design_1 sample = 7 score = 1.153 binder length = 64
design_2 sample = 5 score = 1.224 binder length = 60
design_3 sample = 8 score = 1.0951 binder length = 62
design_4 sample = 6 score = 1.031 binder length = 60

In [49]:
from pathlib import Path

AF2_INPUT = Path("/content/af2_inputs")
AF2_INPUT.mkdir(exist_ok=True)

for design, info in best_sequences.items():

    binder = info["binder"]

    complex_seq = f"{binder}:{TARGET_SEQ}"

    out = AF2_INPUT / f"{design}_best.fasta"

    out.write_text(
        f">{design}_sample{info['sample']}\n"
        f"{complex_seq}\n"
    )

    print(
        out.name,
        "| binder =", len(binder),
        "| target =", len(TARGET_SEQ),
        "| total =", len(binder) + len(TARGET_SEQ)
    )

design_0_best.fasta | binder = 66 | target = 248 | total = 314
design_1_best.fasta | binder = 64 | target = 248 | total = 312
design_2_best.fasta | binder = 60 | target = 248 | total = 308
design_3_best.fasta | binder = 62 | target = 248 | total = 310
design_4_best.fasta | binder = 60 | target = 248 | total = 308

In [50]:
import re
from pathlib import Path

# ============================================================
# Paths
# ============================================================

SEQ_DIR = Path("/content/mpnn_outputs/seqs")
RF_DIR = Path("/content/rfd1_outputs")

# ============================================================
# Convert Chain B target from RFdiffusion PDB -> sequence
# ============================================================

three_to_one = {
    "ALA":"A","ARG":"R","ASN":"N","ASP":"D","CYS":"C",
    "GLN":"Q","GLU":"E","GLY":"G","HIS":"H","ILE":"I",
    "LEU":"L","LYS":"K","MET":"M","PHE":"F","PRO":"P",
    "SER":"S","THR":"T","TRP":"W","TYR":"Y","VAL":"V"
}

target_pdb = RF_DIR / "design_0.pdb"

target_residues = {}

with open(target_pdb) as f:
    for line in f:
        if line.startswith("ATOM") and line[21].strip() == "B":
            key = (int(line[22:26]), line[26])
            target_residues[key] = line[17:20].strip()

TARGET_SEQ = "".join(
    three_to_one.get(target_residues[k], "X")
    for k in sorted(target_residues)
)

print("Target Chain B length:", len(TARGET_SEQ))

# ============================================================
# Select lowest-score ProteinMPNN sample per design
# ============================================================

best_sequences = {}

for fa in sorted(SEQ_DIR.glob("design_*.fa")):

    lines = [
        x.strip()
        for x in fa.read_text().splitlines()
        if x.strip()
    ]

    candidates = []

    for i in range(0, len(lines), 2):

        header = lines[i]
        seq = lines[i + 1]

        # Skip original poly-G sequence
        if "sample=" not in header:
            continue

        sample_match = re.search(r"sample=(\d+)", header)
        score_match = re.search(r"score=([0-9.]+)", header)

        if not sample_match or not score_match:
            continue

        sample = int(sample_match.group(1))
        score = float(score_match.group(1))

        candidates.append((score, sample, seq))

    score, sample, binder_seq = min(
        candidates,
        key=lambda x: x[0]
    )

    best_sequences[fa.stem] = {
        "sample": sample,
        "score": score,
        "binder": binder_seq
    }

    print(
        f"{fa.stem}: "
        f"sample={sample}, "
        f"MPNN score={score:.4f}, "
        f"binder={len(binder_seq)} aa"
    )

Target Chain B length: 248
design_0: sample=5, MPNN score=1.0433, binder=66 aa
design_1: sample=7, MPNN score=1.1530, binder=64 aa
design_2: sample=5, MPNN score=1.2240, binder=60 aa
design_3: sample=8, MPNN score=1.0951, binder=62 aa
design_4: sample=6, MPNN score=1.0310, binder=60 aa

In [51]:
from pathlib import Path

AF2_INPUT = Path("/content/af2_inputs")
AF2_INPUT.mkdir(exist_ok=True)

for design, info in best_sequences.items():

    binder = info["binder"]

    fasta = AF2_INPUT / f"{design}.fasta"

    fasta.write_text(
        f">{design}_sample{info['sample']}\n"
        f"{binder}:{TARGET_SEQ}\n"
    )

    print(
        f"{design}: "
        f"binder={len(binder)} aa + "
        f"target={len(TARGET_SEQ)} aa"
    )

design_0: binder=66 aa + target=248 aa
design_1: binder=64 aa + target=248 aa
design_2: binder=60 aa + target=248 aa
design_3: binder=62 aa + target=248 aa
design_4: binder=60 aa + target=248 aa

In [52]:
for f in sorted(AF2_INPUT.glob("*.fasta")):
    print(f)

/content/af2_inputs/design_0.fasta
/content/af2_inputs/design_0_best.fasta
/content/af2_inputs/design_1.fasta
/content/af2_inputs/design_1_best.fasta
/content/af2_inputs/design_2.fasta
/content/af2_inputs/design_2_best.fasta
/content/af2_inputs/design_3.fasta
/content/af2_inputs/design_3_best.fasta
/content/af2_inputs/design_4.fasta
/content/af2_inputs/design_4_best.fasta

In [53]:
%cd /content

!pip install -q --no-warn-conflicts \
"colabfold[alphafold-minus-jax] @ git+https://github.com/sokrypton/ColabFold"

!python -m colabfold.download

/content
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.1/264.1 kB 20.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 98.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.3/374.3 kB 35.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.0/101.0 kB 11.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB 8.2 MB/s eta 0:00:00
  Building wheel for colabfold (pyproject.toml) ... done
Downloading alphafold2_multimer_v3 weights to /root/.cache/colabfold:   0% 0/4099624960 [00:00<?, ?it/s]/usr/local/lib/python3.13/dist-packages/colabfold/download.py:85: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  file.extractall(path=params_dir)
Downloading alphafold2_multimer_v3 weights to /root/.cache/colabfold: 100% 3.82G/3.82G [03:06<00:00, 21.9MB/s]
Downloading AlphaFold2-ptm weights to /root/.cache/colabfold: 100% 3.47G/3.47G [02:51<00:00, 21.7MB/s]

In [54]:
!colabfold_batch --help | head -30

usage: colabfold_batch [-h] [--msa-only]
                       [--msa-mode {mmseqs2_uniref_env,mmseqs2_uniref_env_envpair,mmseqs2_uniref,single_sequence}]
                       [--pair-mode {unpaired,paired,unpaired_paired}]
                       [--pair-strategy {complete,greedy}] [--templates]
                       [--custom-template-path CUSTOM_TEMPLATE_PATH]
                       [--custom-template-cache-path CUSTOM_TEMPLATE_CACHE_PATH]
                       [--max-template-date MAX_TEMPLATE_DATE]
                       [--max-template-hits MAX_TEMPLATE_HITS]
                       [--pdb-hit-file PDB_HIT_FILE]
                       [--local-pdb-path LOCAL_PDB_PATH]
                       [--num-recycle NUM_RECYCLE]
                       [--recycle-early-stop-tolerance RECYCLE_EARLY_STOP_TOLERANCE]
                       [--num-ensemble NUM_ENSEMBLE] [--num-seeds NUM_SEEDS]
                       [--random-seed RANDOM_SEED] [--num-models {1,2,3,4,5}]
                       [--model-type {auto,alphafold2,alphafold2_ptm,alphafold2_multimer_v1,alphafold2_multimer_v2,alphafold2_multimer_v3,deepfold_v1}]
                       [--model-order MODEL_ORDER]
                       [--initial-guess [INITIAL_GUESS]] [--use-dropout]
                       [--max-seq MAX_SEQ] [--max-extra-seq MAX_EXTRA_SEQ]
                       [--max-msa MAX_MSA] [--disable-cluster-profile]
                       [--calc-extra-ptm] [--no-use-probs-extra] [--data DATA]
                       [--amber] [--num-relax NUM_RELAX]
                       [--relax-max-iterations RELAX_MAX_ITERATIONS]
                       [--relax-tolerance RELAX_TOLERANCE]
                       [--relax-stiffness RELAX_STIFFNESS]
                       [--relax-max-outer-iterations RELAX_MAX_OUTER_ITERATIONS]
                       [--use-gpu-relax]
                       [--rank {auto,plddt,ptm,iptm,multimer}]
                       [--stop-at-score STOP_AT_SCORE]
                       [--jobname-prefix JOBNAME_PREFIX] [--save-all]
                       [--save-recycles] [--save-single-representations]

In [55]:
import jax

print("JAX version:", jax.__version__)
print("Devices:", jax.devices())

JAX version: 0.7.2
Devices: [CudaDevice(id=0)]

In [56]:
from pathlib import Path

AF2_OUTPUT = Path("/content/af2_results")
AF2_OUTPUT.mkdir(exist_ok=True)

print(AF2_OUTPUT)

/content/af2_results

In [58]:
#Alphafold

In [57]:
!rm -rf /content/af2_results
!mkdir -p /content/af2_results

!colabfold_batch \
  /content/af2_inputs \
  /content/af2_results \
  --model-type alphafold2_multimer_v3 \
  --num-recycle 3 \
  --num-models 1 \
  --rank multimer

2026-08-24 12:06:34,997 Running colabfold 1.6.2 (0c788a0e8dca909f2c669784f9dd38e8c9682ff0)

WARNING: You are welcome to use the default MSA server, however keep in mind that it's a
limited shared resource only capable of processing a few thousand MSAs per day. Please
submit jobs only from a single IP address. We reserve the right to limit access to the
server case-by-case when usage exceeds fair use. If you require more MSAs: You can
precompute all MSAs with `colabfold_search` or host your own API and pass it to `--host-url`

2026-08-24 12:06:35,447 Running on GPU
2026-08-24 12:06:35,885 Found 5 citations for tools or databases
2026-08-24 12:06:35,885 Query 1/10: design_2 (length 308)
2026-08-24 12:06:36,971 Sleeping for 7s. Reason: PENDING
2026-08-24 12:06:44,670 Sleeping for 8s. Reason: RUNNING
2026-08-24 12:06:53,370 Sleeping for 5s. Reason: RUNNING
2026-08-24 12:06:59,068 Sleeping for 8s. Reason: RUNNING
2026-08-24 12:07:07,772 Sleeping for 10s. Reason: RUNNING
2026-08-24 12:07:18,496 Sleeping for 6s. Reason: RUNNING
2026-08-24 12:07:25,550 Sleeping for 6s. Reason: RUNNING
2026-08-24 12:07:32,246 Sleeping for 8s. Reason: RUNNING
2026-08-24 12:07:40,948 Sleeping for 5s. Reason: RUNNING
COMPLETE: 100% 300/300 [01:11<00:00,  4.20it/s]
2026-08-24 12:07:48,402 Sleeping for 10s. Reason: PENDING
2026-08-24 12:07:59,101 Sleeping for 5s. Reason: RUNNING
2026-08-24 12:08:04,800 Sleeping for 7s. Reason: RUNNING
2026-08-24 12:08:12,498 Sleeping for 5s. Reason: RUNNING
2026-08-24 12:08:18,211 Sleeping for 8s. Reason: RUNNING
2026-08-24 12:08:26,913 Sleeping for 5s. Reason: RUNNING
2026-08-24 12:08:32,631 Sleeping for 5s. Reason: RUNNING
2026-08-24 12:08:38,334 Sleeping for 8s. Reason: RUNNING
COMPLETE: 100% 300/300 [01:00<00:00,  5.00it/s]
/usr/local/lib/python3.13/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)
2026-08-24 12:09:58,056 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=62.8 pTM=0.58 ipTM=0.129
2026-08-24 12:10:49,816 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=76.9 pTM=0.672 ipTM=0.0944 tol=7.4
2026-08-24 12:11:13,722 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=77.3 pTM=0.682 ipTM=0.101 tol=2.45
2026-08-24 12:11:37,133 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79 pTM=0.688 ipTM=0.106 tol=1.08
2026-08-24 12:11:37,134 alphafold2_multimer_v3_model_1_seed_000 took 154.8s (3 recycles)
2026-08-24 12:11:37,191 reranking models by 'multimer' metric
2026-08-24 12:11:37,192 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79 pTM=0.688 ipTM=0.106 ipSAE=0 pDockQ2=0.0094
2026-08-24 12:11:37,604 Query 2/10: design_2_best (length 308)
COMPLETE: 100% 300/300 [00:01<00:00, 172.64it/s]
COMPLETE: 100% 300/300 [00:01<00:00, 212.10it/s]
2026-08-24 12:12:04,578 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=62.8 pTM=0.58 ipTM=0.129
2026-08-24 12:12:28,270 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=76.9 pTM=0.672 ipTM=0.0944 tol=7.4
2026-08-24 12:12:51,775 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=77.3 pTM=0.682 ipTM=0.101 tol=2.45
2026-08-24 12:13:15,284 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=79 pTM=0.688 ipTM=0.106 tol=1.08
2026-08-24 12:13:15,285 alphafold2_multimer_v3_model_1_seed_000 took 94.1s (3 recycles)
2026-08-24 12:13:15,340 reranking models by 'multimer' metric
2026-08-24 12:13:15,340 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=79 pTM=0.688 ipTM=0.106 ipSAE=0 pDockQ2=0.0094
2026-08-24 12:13:15,979 Query 3/10: design_4 (length 308)
2026-08-24 12:13:16,695 Sleeping for 10s. Reason: PENDING
2026-08-24 12:13:27,397 Sleeping for 10s. Reason: RUNNING
2026-08-24 12:13:38,099 Sleeping for 8s. Reason: RUNNING
2026-08-24 12:13:46,838 Sleeping for 10s. Reason: RUNNING
2026-08-24 12:13:57,540 Sleeping for 9s. Reason: RUNNING
2026-08-24 12:14:07,247 Sleeping for 10s. Reason: RUNNING
2026-08-24 12:14:17,964 Sleeping for 6s. Reason: RUNNING
2026-08-24 12:14:24,661 Sleeping for 10s. Reason: RUNNING
COMPLETE: 100% 300/300 [01:20<00:00,  3.73it/s]
2026-08-24 12:14:37,097 Sleeping for 8s. Reason: PENDING
2026-08-24 12:14:45,797 Sleeping for 5s. Reason: RUNNING
2026-08-24 12:14:51,493 Sleeping for 9s. Reason: RUNNING
2026-08-24 12:15:01,196 Sleeping for 7s. Reason: RUNNING
COMPLETE: 100% 300/300 [00:33<00:00,  9.03it/s]
2026-08-24 12:15:33,846 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=63.9 pTM=0.579 ipTM=0.129
2026-08-24 12:15:57,770 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=77.7 pTM=0.668 ipTM=0.0886 tol=9.33
2026-08-24 12:16:21,126 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=78.2 pTM=0.681 ipTM=0.0962 tol=2.64
2026-08-24 12:16:44,490 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=78.9 pTM=0.686 ipTM=0.0946 tol=1.68
2026-08-24 12:16:44,490 alphafold2_multimer_v3_model_1_seed_000 took 94.5s (3 recycles)
2026-08-24 12:16:44,519 reranking models by 'multimer' metric
2026-08-24 12:16:44,520 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=78.9 pTM=0.686 ipTM=0.0946 ipSAE=0 pDockQ2=0.0092
2026-08-24 12:16:44,903 Query 4/10: design_4_best (length 308)
COMPLETE: 100% 300/300 [00:01<00:00, 172.14it/s]
COMPLETE: 100% 300/300 [00:01<00:00, 213.04it/s]
2026-08-24 12:17:12,016 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=63.9 pTM=0.579 ipTM=0.129
2026-08-24 12:17:35,625 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=77.7 pTM=0.668 ipTM=0.0886 tol=9.33
2026-08-24 12:17:59,045 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=78.2 pTM=0.681 ipTM=0.0962 tol=2.64
2026-08-24 12:18:22,573 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=78.9 pTM=0.686 ipTM=0.0946 tol=1.68
2026-08-24 12:18:22,573 alphafold2_multimer_v3_model_1_seed_000 took 94.1s (3 recycles)
2026-08-24 12:18:22,619 reranking models by 'multimer' metric
2026-08-24 12:18:22,619 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=78.9 pTM=0.686 ipTM=0.0946 ipSAE=0 pDockQ2=0.0092
2026-08-24 12:18:23,008 Query 5/10: design_3 (length 310)
2026-08-24 12:18:23,717 Sleeping for 9s. Reason: PENDING
2026-08-24 12:18:33,424 Sleeping for 10s. Reason: RUNNING
2026-08-24 12:18:44,132 Sleeping for 6s. Reason: RUNNING
2026-08-24 12:18:50,836 Sleeping for 10s. Reason: RUNNING
2026-08-24 12:19:01,539 Sleeping for 5s. Reason: RUNNING
2026-08-24 12:19:07,242 Sleeping for 9s. Reason: RUNNING
2026-08-24 12:19:16,942 Sleeping for 10s. Reason: RUNNING
2026-08-24 12:19:27,643 Sleeping for 10s. Reason: RUNNING
COMPLETE: 100% 300/300 [01:16<00:00,  3.93it/s]
2026-08-24 12:19:40,097 Sleeping for 5s. Reason: PENDING
2026-08-24 12:19:45,808 Sleeping for 10s. Reason: RUNNING
2026-08-24 12:19:56,522 Sleeping for 6s. Reason: RUNNING
2026-08-24 12:20:03,226 Sleeping for 7s. Reason: RUNNING
2026-08-24 12:20:10,927 Sleeping for 10s. Reason: RUNNING
COMPLETE: 100% 300/300 [00:42<00:00,  6.99it/s]
/usr/local/lib/python3.13/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)
2026-08-24 12:21:24,706 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=67.4 pTM=0.603 ipTM=0.113
2026-08-24 12:22:22,342 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=76.8 pTM=0.667 ipTM=0.0876 tol=4.83
2026-08-24 12:22:46,647 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=75.8 pTM=0.673 ipTM=0.095 tol=8.1
2026-08-24 12:23:10,397 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=78.4 pTM=0.683 ipTM=0.1 tol=3.56
2026-08-24 12:23:10,397 alphafold2_multimer_v3_model_1_seed_000 took 167.6s (3 recycles)
2026-08-24 12:23:10,437 reranking models by 'multimer' metric
2026-08-24 12:23:10,437 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=78.4 pTM=0.683 ipTM=0.1 ipSAE=0 pDockQ2=0.0095
2026-08-24 12:23:10,875 Query 6/10: design_3_best (length 310)
COMPLETE: 100% 300/300 [00:01<00:00, 168.85it/s]
COMPLETE: 100% 300/300 [00:01<00:00, 213.03it/s]
2026-08-24 12:23:38,375 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=67.4 pTM=0.603 ipTM=0.113
2026-08-24 12:24:02,520 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=76.8 pTM=0.667 ipTM=0.0876 tol=4.83
2026-08-24 12:24:26,294 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=75.8 pTM=0.673 ipTM=0.095 tol=8.1
2026-08-24 12:24:50,020 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=78.4 pTM=0.683 ipTM=0.1 tol=3.56
2026-08-24 12:24:50,021 alphafold2_multimer_v3_model_1_seed_000 took 95.4s (3 recycles)
2026-08-24 12:24:50,052 reranking models by 'multimer' metric
2026-08-24 12:24:50,052 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=78.4 pTM=0.683 ipTM=0.1 ipSAE=0 pDockQ2=0.0095
2026-08-24 12:24:50,477 Query 7/10: design_1 (length 312)
2026-08-24 12:24:51,188 Sleeping for 5s. Reason: PENDING
2026-08-24 12:24:56,886 Sleeping for 9s. Reason: RUNNING
2026-08-24 12:25:06,587 Sleeping for 8s. Reason: RUNNING
2026-08-24 12:25:15,297 Sleeping for 8s. Reason: RUNNING
2026-08-24 12:25:24,003 Sleeping for 8s. Reason: RUNNING
2026-08-24 12:25:32,704 Sleeping for 6s. Reason: RUNNING
2026-08-24 12:25:39,416 Sleeping for 9s. Reason: RUNNING
2026-08-24 12:25:49,129 Sleeping for 8s. Reason: RUNNING
2026-08-24 12:25:57,828 Sleeping for 8s. Reason: RUNNING
COMPLETE: 100% 300/300 [01:17<00:00,  3.89it/s]
2026-08-24 12:26:08,276 Sleeping for 5s. Reason: PENDING
2026-08-24 12:26:14,003 Sleeping for 7s. Reason: RUNNING
2026-08-24 12:26:21,710 Sleeping for 6s. Reason: RUNNING
2026-08-24 12:26:28,412 Sleeping for 10s. Reason: RUNNING
2026-08-24 12:26:39,124 Sleeping for 6s. Reason: RUNNING
2026-08-24 12:26:45,832 Sleeping for 7s. Reason: RUNNING
COMPLETE: 100% 300/300 [00:46<00:00,  6.43it/s]
/usr/local/lib/python3.13/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)
2026-08-24 12:27:50,062 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=66.8 pTM=0.598 ipTM=0.125
2026-08-24 12:28:43,059 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=75.8 pTM=0.668 ipTM=0.112 tol=9.41
2026-08-24 12:29:07,166 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=75.4 pTM=0.679 ipTM=0.119 tol=3.99
2026-08-24 12:29:30,667 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=74.9 pTM=0.671 ipTM=0.124 tol=0.814
2026-08-24 12:29:30,668 alphafold2_multimer_v3_model_1_seed_000 took 156.0s (3 recycles)
2026-08-24 12:29:30,698 reranking models by 'multimer' metric
2026-08-24 12:29:30,699 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=74.9 pTM=0.671 ipTM=0.124 ipSAE=0 pDockQ2=0.0093
2026-08-24 12:29:31,108 Query 8/10: design_1_best (length 312)
COMPLETE: 100% 300/300 [00:01<00:00, 173.67it/s]
COMPLETE: 100% 300/300 [00:01<00:00, 213.35it/s]
2026-08-24 12:29:58,182 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=66.8 pTM=0.598 ipTM=0.125
2026-08-24 12:30:22,022 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=75.8 pTM=0.668 ipTM=0.112 tol=9.41
2026-08-24 12:30:45,486 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=75.4 pTM=0.679 ipTM=0.119 tol=3.99
2026-08-24 12:31:08,919 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=74.9 pTM=0.671 ipTM=0.124 tol=0.814
2026-08-24 12:31:08,920 alphafold2_multimer_v3_model_1_seed_000 took 94.3s (3 recycles)
2026-08-24 12:31:08,954 reranking models by 'multimer' metric
2026-08-24 12:31:08,954 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=74.9 pTM=0.671 ipTM=0.124 ipSAE=0 pDockQ2=0.0093
2026-08-24 12:31:09,358 Query 9/10: design_0 (length 314)
2026-08-24 12:31:10,069 Sleeping for 6s. Reason: PENDING
2026-08-24 12:31:16,771 Sleeping for 5s. Reason: RUNNING
2026-08-24 12:31:22,476 Sleeping for 8s. Reason: RUNNING
2026-08-24 12:31:31,184 Sleeping for 6s. Reason: RUNNING
2026-08-24 12:31:37,890 Sleeping for 5s. Reason: RUNNING
2026-08-24 12:31:43,614 Sleeping for 10s. Reason: RUNNING
2026-08-24 12:31:54,308 Sleeping for 5s. Reason: RUNNING
2026-08-24 12:32:00,029 Sleeping for 9s. Reason: RUNNING
2026-08-24 12:32:09,742 Sleeping for 10s. Reason: RUNNING
COMPLETE: 100% 300/300 [01:12<00:00,  4.16it/s]
2026-08-24 12:32:22,200 Sleeping for 8s. Reason: PENDING
2026-08-24 12:32:30,899 Sleeping for 6s. Reason: RUNNING
2026-08-24 12:32:37,606 Sleeping for 5s. Reason: RUNNING
2026-08-24 12:32:43,308 Sleeping for 10s. Reason: RUNNING
2026-08-24 12:32:54,013 Sleeping for 7s. Reason: RUNNING
2026-08-24 12:33:01,712 Sleeping for 5s. Reason: RUNNING
2026-08-24 12:33:07,412 Sleeping for 10s. Reason: RUNNING
COMPLETE: 100% 300/300 [00:57<00:00,  5.23it/s]
/usr/local/lib/python3.13/dist-packages/alphafold/model/modules_multimer.py:114: UserWarning: Explicitly requested dtype <class 'jax.numpy.int64'> requested in broadcasted_iota is not available, and will be truncated to dtype int32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/jax-ml/jax#current-gotchas for more.
  iota = jax.lax.broadcasted_iota(jnp.int64, logits.shape, axis)
2026-08-24 12:34:22,016 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=62.7 pTM=0.584 ipTM=0.161
2026-08-24 12:35:21,317 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=75.4 pTM=0.663 ipTM=0.0932 tol=8.45
2026-08-24 12:35:46,159 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=75.8 pTM=0.672 ipTM=0.1 tol=3.63
2026-08-24 12:36:10,356 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=76.1 pTM=0.668 ipTM=0.103 tol=1.94
2026-08-24 12:36:10,357 alphafold2_multimer_v3_model_1_seed_000 took 171.1s (3 recycles)
2026-08-24 12:36:10,388 reranking models by 'multimer' metric
2026-08-24 12:36:10,388 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=76.1 pTM=0.668 ipTM=0.103 ipSAE=0 pDockQ2=0.0092
2026-08-24 12:36:10,796 Query 10/10: design_0_best (length 314)
COMPLETE: 100% 300/300 [00:01<00:00, 170.76it/s]
COMPLETE: 100% 300/300 [00:01<00:00, 213.92it/s]
2026-08-24 12:36:38,711 alphafold2_multimer_v3_model_1_seed_000 recycle=0 pLDDT=62.7 pTM=0.584 ipTM=0.161
2026-08-24 12:37:03,344 alphafold2_multimer_v3_model_1_seed_000 recycle=1 pLDDT=75.4 pTM=0.663 ipTM=0.0932 tol=8.45
2026-08-24 12:37:27,645 alphafold2_multimer_v3_model_1_seed_000 recycle=2 pLDDT=75.8 pTM=0.672 ipTM=0.1 tol=3.63
2026-08-24 12:37:51,899 alphafold2_multimer_v3_model_1_seed_000 recycle=3 pLDDT=76.1 pTM=0.668 ipTM=0.103 tol=1.94
2026-08-24 12:37:51,899 alphafold2_multimer_v3_model_1_seed_000 took 97.4s (3 recycles)
2026-08-24 12:37:51,930 reranking models by 'multimer' metric
2026-08-24 12:37:51,930 rank_001_alphafold2_multimer_v3_model_1_seed_000 pLDDT=76.1 pTM=0.668 ipTM=0.103 ipSAE=0 pDockQ2=0.0092
2026-08-24 12:37:52,350 Done

In [60]:
from pathlib import Path
from Bio.PDB import PDBParser, Superimposer
import numpy as np

RF_DIR = Path("/content/rfd1_outputs")
AF_DIR = Path("/content/af2_results")

parser = PDBParser(QUIET=True)

def get_chain_ca(pdb_file, chain_id="A"):
    structure = parser.get_structure("x", str(pdb_file))

    atoms = []
    residues = []

    for residue in structure[0][chain_id]:
        if "CA" in residue:
            atoms.append(residue["CA"])
            residues.append(residue.id[1])

    return atoms, residues


print("RFdiffusion → AlphaFold2 binder backbone RMSD")
print("=" * 65)

for i in range(5):
    design = f"design_{i}"

    rf_file = RF_DIR / f"{design}.pdb"

    # IMPORTANT: exclude *_best duplicates
    candidates = [
        p for p in AF_DIR.glob(f"{design}_*rank_001*.pdb")
        if f"{design}_best" not in p.name
    ]

    if not candidates:
        print(f"{design}: AF2 structure not found")
        continue

    af_file = candidates[0]

    rf_atoms, _ = get_chain_ca(rf_file, "A")
    af_atoms, _ = get_chain_ca(af_file, "A")

    print(
        f"\n{design}: RF={len(rf_atoms)} aa, "
        f"AF2={len(af_atoms)} aa"
    )

    if len(rf_atoms) != len(af_atoms):
        print("⚠️ Length mismatch — RMSD NOT calculated")
        print("   Need to verify FASTA ↔ RFdiffusion design mapping.")
        continue

    sup = Superimposer()
    sup.set_atoms(rf_atoms, af_atoms)

    print(f"Binder Cα RMSD = {sup.rms:.3f} Å")
    print("AF2:", af_file.name)

RFdiffusion → AlphaFold2 binder backbone RMSD
=================================================================

design_0: RF=66 aa, AF2=66 aa
Binder Cα RMSD = 6.523 Å
AF2: design_0_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

design_1: RF=64 aa, AF2=64 aa
Binder Cα RMSD = 17.339 Å
AF2: design_1_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

design_2: RF=60 aa, AF2=60 aa
Binder Cα RMSD = 6.384 Å
AF2: design_2_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

design_3: RF=62 aa, AF2=62 aa
Binder Cα RMSD = 4.937 Å
AF2: design_3_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

design_4: RF=60 aa, AF2=60 aa
Binder Cα RMSD = 4.330 Å
AF2: design_4_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

In [61]:
# ============================================================
# RFdiffusion -> AlphaFold2 evaluation
# RMSD + binder pLDDT + ipTM + interface PAE + ranking
# ============================================================

from pathlib import Path
import json
import numpy as np
import pandas as pd
import re

RF_DIR = Path("/content/rfd1_outputs")
AF_DIR = Path("/content/af2_results")

DESIGNS = [f"design_{i}" for i in range(5)]

# ------------------------------------------------------------
# 1. Read CA coordinates from PDB
# ------------------------------------------------------------
def get_ca_coords(pdb_file, chain="A"):
    coords = []

    with open(pdb_file) as f:
        for line in f:
            if line.startswith("ATOM"):
                atom = line[12:16].strip()
                ch = line[21].strip()

                if atom == "CA" and ch == chain:
                    x = float(line[30:38])
                    y = float(line[38:46])
                    z = float(line[46:54])

                    coords.append([x, y, z])

    return np.array(coords)


# ------------------------------------------------------------
# 2. Kabsch RMSD
# ------------------------------------------------------------
def kabsch_rmsd(P, Q):

    if len(P) != len(Q):
        raise ValueError(
            f"Different lengths: RF={len(P)}, AF2={len(Q)}"
        )

    P = P - P.mean(axis=0)
    Q = Q - Q.mean(axis=0)

    H = P.T @ Q

    U, S, Vt = np.linalg.svd(H)

    d = np.linalg.det(Vt.T @ U.T)

    D = np.eye(3)
    D[2,2] = d

    R = Vt.T @ D @ U.T

    P_rot = P @ R.T

    return np.sqrt(np.mean(np.sum((P_rot - Q)**2, axis=1)))


# ------------------------------------------------------------
# 3. Mean pLDDT from binder chain A
#    PDB B-factor stores pLDDT
# ------------------------------------------------------------
def binder_plddt(pdb_file, chain="A"):

    values = []

    with open(pdb_file) as f:

        for line in f:

            if not line.startswith("ATOM"):
                continue

            if line[21].strip() != chain:
                continue

            # CA only -> one pLDDT per residue
            if line[12:16].strip() != "CA":
                continue

            try:
                values.append(float(line[60:66]))
            except:
                pass

    if len(values) == 0:
        return np.nan

    return np.mean(values)


# ------------------------------------------------------------
# 4. Find AF2 result files
# ------------------------------------------------------------
def find_af_files(design):

    pdbs = list(
        AF_DIR.glob(
            f"{design}*rank_001*.pdb"
        )
    )

    jsons = list(
        AF_DIR.glob(
            f"{design}*scores*.json"
        )
    )

    # recursive search if results are inside subfolders
    if not pdbs:
        pdbs = list(
            AF_DIR.rglob(
                f"{design}*rank_001*.pdb"
            )
        )

    if not jsons:
        jsons = list(
            AF_DIR.rglob(
                f"{design}*scores*.json"
            )
        )

    return pdbs, jsons


# ------------------------------------------------------------
# 5. Calculate interface PAE
# ------------------------------------------------------------
def interface_pae_from_json(score_file, binder_len):

    with open(score_file) as f:
        data = json.load(f)

    pae = data.get("pae")

    if pae is None:
        pae = data.get("predicted_aligned_error")

    if pae is None:
        return np.nan

    pae = np.array(pae)

    total_len = pae.shape[0]

    if binder_len >= total_len:
        return np.nan

    # Chain A = binder
    # Chain B = target

    A_to_B = pae[:binder_len, binder_len:]
    B_to_A = pae[binder_len:, :binder_len]

    vals = np.concatenate([
        A_to_B.flatten(),
        B_to_A.flatten()
    ])

    return np.mean(vals)


# ------------------------------------------------------------
# 6. Process designs
# ------------------------------------------------------------

rows = []

print("="*75)
print("RFdiffusion -> AlphaFold2 evaluation")
print("="*75)

for design in DESIGNS:

    rf_pdb = RF_DIR / f"{design}.pdb"

    if not rf_pdb.exists():

        print(design, ": RF PDB missing")
        continue


    pdbs, jsons = find_af_files(design)

    if not pdbs:

        print(design, ": AF2 PDB missing")
        continue


    af_pdb = pdbs[0]


    # ---------- RMSD ----------

    rf_ca = get_ca_coords(rf_pdb, "A")

    af_ca = get_ca_coords(af_pdb, "A")


    if len(rf_ca) == len(af_ca) and len(rf_ca) > 0:

        rmsd = kabsch_rmsd(rf_ca, af_ca)

    else:

        rmsd = np.nan


    # ---------- pLDDT ----------

    plddt = binder_plddt(
        af_pdb,
        "A"
    )


    # ---------- ipTM + PAE ----------

    iptm = np.nan
    interface_pae = np.nan


    if jsons:

        score_file = jsons[0]

        with open(score_file) as f:

            data = json.load(f)


        # ipTM

        for key in [
            "iptm",
            "ipTM",
            "iptm_score"
        ]:

            if key in data:

                iptm = float(data[key])

                break


        # Interface PAE

        interface_pae = interface_pae_from_json(
            score_file,
            len(af_ca)
        )


    rows.append({

        "Design": design,

        "Binder_length":
            len(af_ca),

        "RMSD_A":
            rmsd,

        "Binder_pLDDT":
            plddt,

        "ipTM":
            iptm,

        "Interface_PAE_A":
            interface_pae

    })


# ------------------------------------------------------------
# 7. Create dataframe
# ------------------------------------------------------------

df = pd.DataFrame(rows)


# ------------------------------------------------------------
# 8. Ranking
#
# lower RMSD = better
# higher pLDDT = better
# higher ipTM = better
# lower PAE = better
# ------------------------------------------------------------

if len(df) > 0:

    df["RMSD_rank"] = \
        df["RMSD_A"].rank(
            ascending=True
        )

    df["pLDDT_rank"] = \
        df["Binder_pLDDT"].rank(
            ascending=False
        )

    df["ipTM_rank"] = \
        df["ipTM"].rank(
            ascending=False
        )

    df["PAE_rank"] = \
        df["Interface_PAE_A"].rank(
            ascending=True
        )


    # Mean rank
    df["Mean_rank"] = df[
        [
            "RMSD_rank",
            "pLDDT_rank",
            "ipTM_rank",
            "PAE_rank"
        ]
    ].mean(axis=1)


    df["Final_rank"] = \
        df["Mean_rank"].rank(
            method="min"
        ).astype(int)


    df = df.sort_values(
        "Final_rank"
    )


    # prettier output

    for col in [
        "RMSD_A",
        "Binder_pLDDT",
        "ipTM",
        "Interface_PAE_A",
        "Mean_rank"
    ]:

        df[col] = \
            df[col].round(3)


# ------------------------------------------------------------
# 9. Display
# ------------------------------------------------------------

print("\nFINAL RANKING\n")

display(
    df[
        [
            "Final_rank",
            "Design",
            "Binder_length",
            "RMSD_A",
            "Binder_pLDDT",
            "ipTM",
            "Interface_PAE_A",
            "Mean_rank"
        ]
    ]
)


# ------------------------------------------------------------
# 10. Save CSV
# ------------------------------------------------------------

OUTPUT = "/content/binder_evaluation.csv"

df.to_csv(
    OUTPUT,
    index=False
)

print("\nSaved:")
print(OUTPUT)

===========================================================================
RFdiffusion -> AlphaFold2 evaluation
===========================================================================

FINAL RANKING

,Final_rank,Design,Binder_length,RMSD_A,Binder_pLDDT,ipTM,Interface_PAE_A,Mean_rank
2,1,design_2,60,6.384,44.253,0.11,27.063,2.250
1,2,design_1,64,17.339,38.251,0.12,26.079,3.000
4,2,design_4,60,4.330,44.980,0.09,27.494,3.000
3,4,design_3,62,4.937,43.121,0.10,27.396,3.125
0,5,design_0,66,6.523,40.832,0.10,27.260,3.625

Saved:
/content/binder_evaluation.csv

In [62]:
#Rosetta

In [63]:
import shutil
import importlib.util
from pathlib import Path

print("=== Rosetta / PyRosetta check ===")

# PyRosetta
pyrosetta_found = importlib.util.find_spec("pyrosetta") is not None
print("PyRosetta:", "FOUND" if pyrosetta_found else "NOT FOUND")

# Rosetta command-line executables
commands = [
    "rosetta_scripts.default.linuxgccrelease",
    "InterfaceAnalyzer.default.linuxgccrelease",
    "relax.default.linuxgccrelease",
]

for cmd in commands:
    path = shutil.which(cmd)
    print(f"{cmd}: {path if path else 'NOT FOUND'}")

# Check our AF2 structures
AF_DIR = Path("/content/af2_results")

print("\n=== AlphaFold2 PDBs ===")

for i in range(5):
    design = f"design_{i}"
    files = list(AF_DIR.rglob(
        f"{design}_unrelaxed_rank_001*.pdb"
    ))

    if files:
        print(f"✓ {design}: {files[0]}")
    else:
        print(f"✗ {design}: PDB not found")

=== Rosetta / PyRosetta check ===
PyRosetta: NOT FOUND
rosetta_scripts.default.linuxgccrelease: NOT FOUND
InterfaceAnalyzer.default.linuxgccrelease: NOT FOUND
relax.default.linuxgccrelease: NOT FOUND

=== AlphaFold2 PDBs ===
✓ design_0: /content/af2_results/design_0_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
✓ design_1: /content/af2_results/design_1_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
✓ design_2: /content/af2_results/design_2_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
✓ design_3: /content/af2_results/design_3_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
✓ design_4: /content/af2_results/design_4_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

In [64]:
import sys
print("Python:", sys.version)

Python: 3.13.15 (main, Aug  6 2026, 11:06:23) [GCC 11.4.0]

In [65]:
!pip install -q pyrosetta \
  --find-links https://west.rosettacommons.org/pyrosetta/quarterly/release

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 GB 419.0 kB/s eta 0:00:00

In [66]:
import pyrosetta

print("PyRosetta imported successfully")
print("Version:", pyrosetta.version())

pyrosetta.init("-mute all")

print(" PyRosetta initialized successfully")

PyRosetta imported successfully
Version: ┌───────────────────────────────────────────────────────────────────────────────┐
│                                  PyRosetta-4                                  │
│               Created in JHU by Sergey Lyskov and PyRosetta Team              │
│               (C) Copyright Rosetta Commons Member Institutions               │
│                                                                               │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRES PURCHASE OF A LICENSE │
│          See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└───────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2026 [Rosetta PyRosetta4.Release.python313.ubuntu 2026.29+releasequarterly.80a0635615099e1b918474a63acba7b1de6fd107 2026-07-14T16:24:11] retrieved from: http://www.pyrosetta.org
┌───────────────────────────────────────────────────────────────────────────────┐
│                                  PyRosetta-4                                  │
│               Created in JHU by Sergey Lyskov and PyRosetta Team              │
│               (C) Copyright Rosetta Commons Member Institutions               │
│                                                                               │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRES PURCHASE OF A LICENSE │
│          See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└───────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2026 [Rosetta PyRosetta4.Release.python313.ubuntu 2026.29+releasequarterly.80a0635615099e1b918474a63acba7b1de6fd107 2026-07-14T16:24:11] retrieved from: http://www.pyrosetta.org
 PyRosetta initialized successfully

In [67]:
from pathlib import Path
from Bio.PDB import PDBParser

AF_DIR = Path("/content/af2_results")

parser = PDBParser(QUIET=True)

print("=" * 70)
print("AlphaFold2 complexes for Rosetta")
print("=" * 70)

af2_pdbs = {}

for i in range(5):
    design = f"design_{i}"

    files = list(AF_DIR.glob(
        f"{design}_unrelaxed_rank_001*.pdb"
    ))

    if not files:
        print(f" {design}: not found")
        continue

    pdb = files[0]
    af2_pdbs[design] = pdb

    structure = parser.get_structure(design, pdb)
    model = structure[0]

    print(f"\n{design}")
    print("PDB:", pdb)

    for chain in model:
        residues = [
            r for r in chain
            if r.id[0] == " "
        ]

        print(
            f"  Chain {chain.id}: "
            f"{len(residues)} residues"
        )

======================================================================
AlphaFold2 complexes for Rosetta
======================================================================

design_0
PDB: /content/af2_results/design_0_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
  Chain A: 66 residues
  Chain B: 248 residues

design_1
PDB: /content/af2_results/design_1_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
  Chain A: 64 residues
  Chain B: 248 residues

design_2
PDB: /content/af2_results/design_2_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
  Chain A: 60 residues
  Chain B: 248 residues

design_3
PDB: /content/af2_results/design_3_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
  Chain A: 62 residues
  Chain B: 248 residues

design_4
PDB: /content/af2_results/design_4_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
  Chain A: 60 residues
  Chain B: 248 residues

In [69]:
from pathlib import Path

AF_DIR = Path("/content/af2_results")
ROSETTA_DIR = Path("/content/rosetta_results")

print("AF2 directory exists     :", AF_DIR.exists())
print("Rosetta directory exists :", ROSETTA_DIR.exists())

print("\n=== AF2 PDBs ===")
for i in range(5):
    files = list(AF_DIR.glob(f"design_{i}_unrelaxed_rank_001*.pdb"))
    print(f"design_{i}:", files[0] if files else "MISSING")

print("\n=== Relaxed PDBs ===")
for i in range(5):
    f = ROSETTA_DIR / f"design_{i}_relaxed.pdb"
    print(f"design_{i}:", "FOUND" if f.exists() else "MISSING")

AF2 directory exists     : True
Rosetta directory exists : False

=== AF2 PDBs ===
design_0: /content/af2_results/design_0_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
design_1: /content/af2_results/design_1_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
design_2: /content/af2_results/design_2_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
design_3: /content/af2_results/design_3_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
design_4: /content/af2_results/design_4_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb

=== Relaxed PDBs ===
design_0: MISSING
design_1: MISSING
design_2: MISSING
design_3: MISSING
design_4: MISSING

In [70]:
from pathlib import Path
import pandas as pd
import pyrosetta
from pyrosetta import pose_from_pdb
from pyrosetta.rosetta.protocols.relax import FastRelax

# ============================================================
# Paths
# ============================================================

AF_DIR = Path("/content/af2_results")
OUT_DIR = Path("/content/rosetta_results")

OUT_DIR.mkdir(parents=True, exist_ok=True)

print("Output directory:", OUT_DIR)
print("Exists:", OUT_DIR.exists())

# ============================================================
# Score function
# ============================================================

scorefxn = pyrosetta.get_fa_scorefxn()

summary = []

print("\n" + "="*70)
print("Rosetta FastRelax")
print("="*70)

# ============================================================
# Process design_0 - design_4
# ============================================================

for i in range(5):

    design = f"design_{i}"

    pdbs = list(
        AF_DIR.glob(
            f"{design}_unrelaxed_rank_001*.pdb"
        )
    )

    if not pdbs:
        print(f"\n❌ {design}: AF2 PDB not found")
        continue

    input_pdb = pdbs[0]

    output_pdb = (
        OUT_DIR /
        f"{design}_relaxed.pdb"
    )

    print("\n" + "="*60)
    print(f"Processing {design}")
    print("="*60)

    print("Input :", input_pdb)
    print("Output:", output_pdb)

    try:

        # ---------------------------
        # Load AF2 complex
        # ---------------------------

        pose = pose_from_pdb(
            str(input_pdb)
        )

        print(
            "Residues:",
            pose.total_residue()
        )

        # ---------------------------
        # Score before
        # ---------------------------

        score_before = scorefxn(pose)

        print(
            f"Score before: "
            f"{score_before:.3f} REU"
        )

        # ---------------------------
        # FastRelax
        # ---------------------------

        relax = FastRelax(
            scorefxn,
            3
        )

        # Keep close to AF2 coordinates
        relax.constrain_relax_to_start_coords(
            True
        )

        print("Running FastRelax...")

        relax.apply(pose)

        # ---------------------------
        # Score after
        # ---------------------------

        score_after = scorefxn(pose)

        print(
            f"Score after : "
            f"{score_after:.3f} REU"
        )

        # ---------------------------
        # SAVE IMMEDIATELY
        # ---------------------------

        pose.dump_pdb(
            str(output_pdb)
        )

        # Verify
        if output_pdb.exists():

            size_mb = (
                output_pdb.stat().st_size /
                1024**2
            )

            print(
                f"✅ Saved "
                f"({size_mb:.2f} MB)"
            )

        else:

            raise RuntimeError(
                "PDB was not written"
            )

        summary.append({

            "Design":
                design,

            "Score_before_REU":
                score_before,

            "Score_after_REU":
                score_after,

            "Delta_REU":
                score_after -
                score_before

        })

    except Exception as e:

        print(
            f"❌ ERROR in {design}:"
        )

        print(
            type(e).__name__,
            str(e)
        )


# ============================================================
# Summary
# ============================================================

relax_df = pd.DataFrame(summary)

print("\n" + "="*70)
print("FASTRELAX SUMMARY")
print("="*70)

display(relax_df)

# ============================================================
# Verify files
# ============================================================

print("\nGenerated PDB files:")

for i in range(5):

    f = (
        OUT_DIR /
        f"design_{i}_relaxed.pdb"
    )

    print(
        f"{f.name}:",
        "✅ FOUND"
        if f.exists()
        else "❌ MISSING"
    )

# Save summary
if len(relax_df) > 0:

    relax_df.to_csv(
        OUT_DIR /
        "fastrelax_scores.csv",
        index=False
    )

Output directory: /content/rosetta_results
Exists: True

======================================================================
Rosetta FastRelax
======================================================================

============================================================
Processing design_0
============================================================
Input : /content/af2_results/design_0_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
Output: /content/rosetta_results/design_0_relaxed.pdb
Residues: 314
Score before: 3017.280 REU
Running FastRelax...
Score after : -788.922 REU
✅ Saved (0.39 MB)

============================================================
Processing design_1
============================================================
Input : /content/af2_results/design_1_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
Output: /content/rosetta_results/design_1_relaxed.pdb
Residues: 312
Score before: 9875.633 REU
Running FastRelax...
Score after : -810.519 REU
✅ Saved (0.39 MB)

============================================================
Processing design_2
============================================================
Input : /content/af2_results/design_2_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
Output: /content/rosetta_results/design_2_relaxed.pdb
Residues: 308
Score before: 1124.146 REU
Running FastRelax...
Score after : -787.824 REU
✅ Saved (0.39 MB)

============================================================
Processing design_3
============================================================
Input : /content/af2_results/design_3_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
Output: /content/rosetta_results/design_3_relaxed.pdb
Residues: 310
Score before: 4718.591 REU
Running FastRelax...
Score after : -777.906 REU
✅ Saved (0.38 MB)

============================================================
Processing design_4
============================================================
Input : /content/af2_results/design_4_unrelaxed_rank_001_alphafold2_multimer_v3_model_1_seed_000.pdb
Output: /content/rosetta_results/design_4_relaxed.pdb
Residues: 308
Score before: 7356.676 REU
Running FastRelax...
Score after : -766.642 REU
✅ Saved (0.38 MB)

======================================================================
FASTRELAX SUMMARY
======================================================================

     Design  Score_before_REU  Score_after_REU     Delta_REU
0  design_0       3017.280401      -788.922049  -3806.202451
1  design_1       9875.632941      -810.518958 -10686.151899
2  design_2       1124.146167      -787.824478  -1911.970645
3  design_3       4718.591108      -777.906141  -5496.497249
4  design_4       7356.676245      -766.642476  -8123.318721

Generated PDB files:
design_0_relaxed.pdb: ✅ FOUND
design_1_relaxed.pdb: ✅ FOUND
design_2_relaxed.pdb: ✅ FOUND
design_3_relaxed.pdb: ✅ FOUND
design_4_relaxed.pdb: ✅ FOUND

In [72]:
# ============================================================
# Cell 5 FIXED — Rosetta InterfaceAnalyzer
# PyRosetta 2026 compatible
#
# Chain A = binder
# Chain B = target
# ============================================================

from pathlib import Path
import pandas as pd
import numpy as np

from pyrosetta import pose_from_pdb
from pyrosetta.rosetta.protocols.analysis import InterfaceAnalyzerMover


ROSETTA_DIR = Path("/content/rosetta_results")
ROSETTA_DIR.mkdir(parents=True, exist_ok=True)


print("=" * 75)
print("Rosetta Interface Analysis")
print("Chain A = Binder")
print("Chain B = Target")
print("=" * 75)


# ============================================================
# Helper
# ============================================================

def safe_get(obj, names):

    for name in names:

        if hasattr(obj, name):

            try:
                value = getattr(obj, name)()

                return float(value)

            except:
                pass

    return np.nan


# ============================================================
# Analyze designs
# ============================================================

results = []


for i in range(5):

    design = f"design_{i}"

    pdb_file = (
        ROSETTA_DIR /
        f"{design}_relaxed.pdb"
    )


    print("\n" + "=" * 65)
    print(design)
    print("=" * 65)


    if not pdb_file.exists():

        print("❌ Missing:", pdb_file)

        continue


    # --------------------------------------------------------
    # Load PDB
    # --------------------------------------------------------

    pose = pose_from_pdb(
        str(pdb_file)
    )


    print("PDB:", pdb_file)

    print(
        "Total residues:",
        pose.total_residue()
    )


    # --------------------------------------------------------
    # Show chains
    # --------------------------------------------------------

    pdb_info = pose.pdb_info()

    chains = []

    for r in range(
        1,
        pose.total_residue() + 1
    ):

        c = pdb_info.chain(r)

        if c not in chains:
            chains.append(c)


    print(
        "Chains:",
        chains
    )


    # --------------------------------------------------------
    # IMPORTANT
    #
    # For a 2-chain A/B complex,
    # jump 1 connects chain A and chain B
    # --------------------------------------------------------

    interface_jump = 1


    iam = InterfaceAnalyzerMover(
        interface_jump
    )


    # --------------------------------------------------------
    # Settings
    # --------------------------------------------------------

    try:
        iam.set_compute_packstat(True)
    except:
        pass

    try:
        iam.set_compute_interface_energy(True)
    except:
        pass

    try:
        iam.set_calc_dSASA(True)
    except:
        pass

    try:
        iam.set_calc_hbond_sasaE(True)
    except:
        pass

    try:
        iam.set_compute_interface_sc(True)
    except:
        pass


    print(
        "Running InterfaceAnalyzer "
        "(jump 1 = A/B interface)..."
    )


    # --------------------------------------------------------
    # Run
    # --------------------------------------------------------

    try:

        iam.apply(pose)

    except Exception as e:

        print(
            "❌ InterfaceAnalyzer failed:"
        )

        print(
            type(e).__name__,
            e
        )

        continue


    # ========================================================
    # Extract metrics
    # ========================================================

    dG = safe_get(
        iam,
        [
            "get_interface_dG",
            "get_separated_interface_energy"
        ]
    )


    dSASA = safe_get(
        iam,
        [
            "get_interface_delta_sasa",
            "get_interface_dSASA"
        ]
    )


    SC = safe_get(
        iam,
        [
            "get_sc_value",
            "get_interface_sc"
        ]
    )


    packstat = safe_get(
        iam,
        [
            "get_interface_packstat",
            "get_packstat"
        ]
    )


    unsat = safe_get(
        iam,
        [
            "get_interface_delta_hbond_unsat",
            "get_delta_unsat_hbonds"
        ]
    )


    # ========================================================
    # Print results
    # ========================================================

    print("\nRESULTS")

    print(
        f"ΔG       : {dG:.3f} REU"
    )

    print(
        f"dSASA    : {dSASA:.3f} Å²"
    )

    print(
        f"SC       : {SC:.3f}"
    )

    print(
        f"Packstat : {packstat:.3f}"
    )

    print(
        f"Unsat HB : {unsat:.3f}"
    )


    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    results.append(
        {
            "Design": design,

            "Rosetta_dG_REU":
                dG,

            "dSASA_A2":
                dSASA,

            "Shape_complementarity":
                SC,

            "Interface_packstat":
                packstat,

            "Unsat_Hbond":
                unsat
        }
    )


    print("✅ Complete")


# ============================================================
# Results table
# ============================================================

rosetta_df = pd.DataFrame(
    results
)


print("\n" + "=" * 75)
print("ROSETTA INTERFACE RESULTS")
print("=" * 75)


if len(rosetta_df) > 0:

    display(
        rosetta_df.round(3)
    )


    csv_file = (
        ROSETTA_DIR /
        "rosetta_interface_scores.csv"
    )


    rosetta_df.to_csv(
        csv_file,
        index=False
    )


    print("\n✅ Saved:")
    print(csv_file)


else:

    print(
        "❌ No interface results generated"
    )

===========================================================================
Rosetta Interface Analysis
Chain A = Binder
Chain B = Target
===========================================================================

=================================================================
design_0
=================================================================
PDB: /content/rosetta_results/design_0_relaxed.pdb
Total residues: 314
Chains: ['A', 'B']
Running InterfaceAnalyzer (jump 1 = A/B interface)...

RESULTS
ΔG       : -32.826 REU
dSASA    : 1541.773 Å²
SC       : nan
Packstat : 0.660
Unsat HB : 5.000
✅ Complete

=================================================================
design_1
=================================================================
PDB: /content/rosetta_results/design_1_relaxed.pdb
Total residues: 312
Chains: ['A', 'B']
Running InterfaceAnalyzer (jump 1 = A/B interface)...

RESULTS
ΔG       : -67.808 REU
dSASA    : 2440.553 Å²
SC       : nan
Packstat : 0.584
Unsat HB : 12.000
✅ Complete

=================================================================
design_2
=================================================================
PDB: /content/rosetta_results/design_2_relaxed.pdb
Total residues: 308
Chains: ['A', 'B']
Running InterfaceAnalyzer (jump 1 = A/B interface)...

RESULTS
ΔG       : -42.924 REU
dSASA    : 1801.518 Å²
SC       : nan
Packstat : 0.602
Unsat HB : 8.000
✅ Complete

=================================================================
design_3
=================================================================
PDB: /content/rosetta_results/design_3_relaxed.pdb
Total residues: 310
Chains: ['A', 'B']
Running InterfaceAnalyzer (jump 1 = A/B interface)...

RESULTS
ΔG       : -36.724 REU
dSASA    : 1175.386 Å²
SC       : nan
Packstat : 0.672
Unsat HB : 4.000
✅ Complete

=================================================================
design_4
=================================================================
PDB: /content/rosetta_results/design_4_relaxed.pdb
Total residues: 308
Chains: ['A', 'B']
Running InterfaceAnalyzer (jump 1 = A/B interface)...

RESULTS
ΔG       : 0.000 REU
dSASA    : 0.000 Å²
SC       : nan
Packstat : 0.000
Unsat HB : 0.000
✅ Complete

===========================================================================
ROSETTA INTERFACE RESULTS
===========================================================================

,Design,Rosetta_dG_REU,dSASA_A2,Shape_complementarity,Interface_packstat,Unsat_Hbond
0,design_0,-32.826,1541.773,NaN,0.660,5.0
1,design_1,-67.808,2440.553,NaN,0.584,12.0
2,design_2,-42.924,1801.518,NaN,0.602,8.0
3,design_3,-36.724,1175.386,NaN,0.672,4.0
4,design_4,0.000,0.000,NaN,0.000,0.0

✅ Saved:
/content/rosetta_results/rosetta_interface_scores.csv

In [73]:
from pathlib import Path
import numpy as np

ROSETTA_DIR = Path("/content/rosetta_results")

def get_atoms(pdb_file, chain):
    xyz = []

    with open(pdb_file) as f:
        for line in f:
            if not line.startswith("ATOM"):
                continue

            if line[21].strip() != chain:
                continue

            atom = line[12:16].strip()

            # heavy atoms only
            if atom.startswith("H"):
                continue

            xyz.append([
                float(line[30:38]),
                float(line[38:46]),
                float(line[46:54])
            ])

    return np.array(xyz)


print("A-B interface geometry")
print("=" * 60)

for i in range(5):

    design = f"design_{i}"
    pdb = ROSETTA_DIR / f"{design}_relaxed.pdb"

    A = get_atoms(pdb, "A")
    B = get_atoms(pdb, "B")

    # all pairwise distances
    d = np.linalg.norm(
        A[:, None, :] - B[None, :, :],
        axis=2
    )

    min_dist = d.min()

    contacts_5A = np.sum(d < 5.0)

    contacts_8A = np.sum(d < 8.0)

    print(
        f"{design}: "
        f"min A-B = {min_dist:.2f} Å | "
        f"contacts <5Å = {contacts_5A} | "
        f"contacts <8Å = {contacts_8A}"
    )

A-B interface geometry
============================================================
design_0: min A-B = 2.16 Å | contacts <5Å = 1267 | contacts <8Å = 8727
design_1: min A-B = 1.87 Å | contacts <5Å = 2216 | contacts <8Å = 14186
design_2: min A-B = 2.11 Å | contacts <5Å = 1445 | contacts <8Å = 9588
design_3: min A-B = 1.80 Å | contacts <5Å = 1032 | contacts <8Å = 6827
design_4: min A-B = 12.98 Å | contacts <5Å = 0 | contacts <8Å = 0

In [74]:
# ============================================================
# FINAL BINDER RANKING
# RFdiffusion + ProteinMPNN + AlphaFold2 + Rosetta
# ============================================================

from pathlib import Path
import json
import numpy as np
import pandas as pd
from Bio.PDB import PDBParser, Superimposer

RF_DIR = Path("/content/rfd1_outputs")
AF_DIR = Path("/content/af2_results")
ROSETTA_DIR = Path("/content/rosetta_results")

DESIGNS = [f"design_{i}" for i in range(5)]

parser = PDBParser(QUIET=True)

# ============================================================
# 1) RMSD
# ============================================================

def get_chain_ca_atoms(pdb_file, chain_id="A"):
    structure = parser.get_structure("x", str(pdb_file))
    atoms = []

    for residue in structure[0][chain_id]:
        if "CA" in residue:
            atoms.append(residue["CA"])

    return atoms


def calc_rmsd(rf_pdb, af_pdb):
    rf_atoms = get_chain_ca_atoms(rf_pdb, "A")
    af_atoms = get_chain_ca_atoms(af_pdb, "A")

    if len(rf_atoms) != len(af_atoms) or len(rf_atoms) == 0:
        return np.nan

    sup = Superimposer()
    sup.set_atoms(rf_atoms, af_atoms)

    return float(sup.rms)


# ============================================================
# 2) Binder pLDDT from AF2 PDB B-factor
# ============================================================

def binder_plddt(pdb_file):
    vals = []

    with open(pdb_file) as f:
        for line in f:
            if (
                line.startswith("ATOM")
                and line[21].strip() == "A"
                and line[12:16].strip() == "CA"
            ):
                try:
                    vals.append(float(line[60:66]))
                except:
                    pass

    return np.mean(vals) if vals else np.nan


# ============================================================
# 3) ipTM + interface PAE
# ============================================================

def get_af2_json(design):
    files = list(AF_DIR.glob(f"{design}_scores_rank_001*.json"))

    if not files:
        files = list(AF_DIR.rglob(f"{design}_scores_rank_001*.json"))

    return files[0] if files else None


def get_af2_pdb(design):
    files = [
        p for p in AF_DIR.glob(f"{design}_unrelaxed_rank_001*.pdb")
        if "_best" not in p.name
    ]

    if not files:
        files = [
            p for p in AF_DIR.rglob(f"{design}_unrelaxed_rank_001*.pdb")
            if "_best" not in p.name
        ]

    return files[0] if files else None


def get_iptm_and_interface_pae(score_json, binder_len):
    if score_json is None:
        return np.nan, np.nan

    with open(score_json) as f:
        data = json.load(f)

    iptm = np.nan
    for key in ["iptm", "ipTM", "iptm_score"]:
        if key in data:
            iptm = float(data[key])
            break

    pae = data.get("pae", data.get("predicted_aligned_error"))

    if pae is None:
        return iptm, np.nan

    pae = np.array(pae)

    if binder_len >= pae.shape[0]:
        return iptm, np.nan

    A_to_B = pae[:binder_len, binder_len:]
    B_to_A = pae[binder_len:, :binder_len]

    interface_pae = np.mean(
        np.concatenate([
            A_to_B.flatten(),
            B_to_A.flatten()
        ])
    )

    return iptm, float(interface_pae)


# ============================================================
# 4) Rosetta scores
# ============================================================

rosetta_csv = ROSETTA_DIR / "rosetta_interface_scores.csv"

if rosetta_csv.exists():
    rosetta_scores = pd.read_csv(rosetta_csv)
else:
    rosetta_scores = pd.DataFrame()


# ============================================================
# 5) Interface geometry
# ============================================================

def get_heavy_atoms(pdb_file, chain):
    coords = []

    with open(pdb_file) as f:
        for line in f:
            if not line.startswith("ATOM"):
                continue

            if line[21].strip() != chain:
                continue

            atom = line[12:16].strip()

            if atom.startswith("H"):
                continue

            coords.append([
                float(line[30:38]),
                float(line[38:46]),
                float(line[46:54])
            ])

    return np.array(coords)


def interface_geometry(pdb_file):
    A = get_heavy_atoms(pdb_file, "A")
    B = get_heavy_atoms(pdb_file, "B")

    if len(A) == 0 or len(B) == 0:
        return np.nan, 0, 0

    d = np.linalg.norm(
        A[:, None, :] - B[None, :, :],
        axis=2
    )

    return (
        float(d.min()),
        int(np.sum(d < 5.0)),
        int(np.sum(d < 8.0))
    )


# ============================================================
# 6) Collect all metrics
# ============================================================

rows = []

for design in DESIGNS:

    rf_pdb = RF_DIR / f"{design}.pdb"
    af_pdb = get_af2_pdb(design)
    ros_pdb = ROSETTA_DIR / f"{design}_relaxed.pdb"

    if not rf_pdb.exists() or af_pdb is None:
        print(f"{design}: missing RF or AF2 file")
        continue

    binder_len = len(get_chain_ca_atoms(af_pdb, "A"))

    rmsd = calc_rmsd(rf_pdb, af_pdb)
    plddt = binder_plddt(af_pdb)

    score_json = get_af2_json(design)
    iptm, interface_pae = get_iptm_and_interface_pae(
        score_json,
        binder_len
    )

    # Rosetta
    ros_row = None

    if not rosetta_scores.empty:
        match = rosetta_scores[
            rosetta_scores["Design"] == design
        ]

        if len(match):
            ros_row = match.iloc[0]

    dG = np.nan
    dSASA = np.nan
    packstat = np.nan
    unsat = np.nan

    if ros_row is not None:
        dG = ros_row.get("Rosetta_dG_REU", np.nan)
        dSASA = ros_row.get("dSASA_A2", np.nan)
        packstat = ros_row.get("Interface_packstat", np.nan)
        unsat = ros_row.get("Unsat_Hbond", np.nan)

    # Geometry
    if ros_pdb.exists():
        min_ab, contacts5, contacts8 = interface_geometry(ros_pdb)
    else:
        min_ab, contacts5, contacts8 = np.nan, 0, 0

    # Reject obvious non-interface
    rejected = (
        contacts8 == 0
        or (not np.isnan(min_ab) and min_ab > 8.0)
        or (not np.isnan(dSASA) and dSASA == 0)
    )

    rows.append({
        "Design": design,
        "Binder_length": binder_len,

        "RMSD_A": rmsd,
        "Binder_pLDDT": plddt,
        "ipTM": iptm,
        "Interface_PAE": interface_pae,

        "Rosetta_dG_REU": dG,
        "dSASA_A2": dSASA,
        "Packstat": packstat,
        "Unsat_Hbond": unsat,

        "Min_AB_A": min_ab,
        "Contacts_lt5A": contacts5,
        "Contacts_lt8A": contacts8,

        "Rejected_no_interface": rejected
    })


df = pd.DataFrame(rows)


# ============================================================
# 7) Rank only non-rejected designs
# ============================================================

valid = df[~df["Rejected_no_interface"]].copy()

# Lower = better
valid["RMSD_rank"] = valid["RMSD_A"].rank(ascending=True)
valid["PAE_rank"] = valid["Interface_PAE"].rank(ascending=True)
valid["dG_rank"] = valid["Rosetta_dG_REU"].rank(ascending=True)
valid["Unsat_rank"] = valid["Unsat_Hbond"].rank(ascending=True)
valid["MinAB_rank"] = valid["Min_AB_A"].rank(ascending=True)

# Higher = better
valid["pLDDT_rank"] = valid["Binder_pLDDT"].rank(ascending=False)
valid["ipTM_rank"] = valid["ipTM"].rank(ascending=False)
valid["dSASA_rank"] = valid["dSASA_A2"].rank(ascending=False)
valid["Packstat_rank"] = valid["Packstat"].rank(ascending=False)
valid["Contact_rank"] = valid["Contacts_lt5A"].rank(ascending=False)


# ============================================================
# 8) Weighted final score
#
# AlphaFold interface confidence + fold consistency
# are weighted more than raw Rosetta contact size.
# ============================================================

rank_cols = {
    "RMSD_rank": 2.0,
    "pLDDT_rank": 1.5,
    "ipTM_rank": 2.5,
    "PAE_rank": 2.5,
    "dG_rank": 1.5,
    "dSASA_rank": 0.75,
    "Packstat_rank": 1.0,
    "Unsat_rank": 1.0,
    "MinAB_rank": 0.5,
    "Contact_rank": 0.5
}

numerator = 0
denominator = 0

for col, weight in rank_cols.items():
    if col in valid.columns:
        numerator = numerator + valid[col] * weight
        denominator += weight

valid["Weighted_rank_score"] = numerator / denominator

valid["Final_rank"] = valid["Weighted_rank_score"].rank(
    method="min",
    ascending=True
).astype(int)


# ============================================================
# 9) Merge rank back
# ============================================================

df = df.merge(
    valid[
        [
            "Design",
            "Weighted_rank_score",
            "Final_rank"
        ]
    ],
    on="Design",
    how="left"
)


# ============================================================
# 10) Pretty table
# ============================================================

for col in [
    "RMSD_A",
    "Binder_pLDDT",
    "ipTM",
    "Interface_PAE",
    "Rosetta_dG_REU",
    "dSASA_A2",
    "Packstat",
    "Unsat_Hbond",
    "Min_AB_A",
    "Weighted_rank_score"
]:
    if col in df.columns:
        df[col] = pd.to_numeric(
            df[col],
            errors="coerce"
        ).round(3)


df = df.sort_values(
    ["Rejected_no_interface", "Final_rank"],
    na_position="last"
)


print("=" * 100)
print("FINAL BINDER RANKING")
print("=" * 100)

display(
    df[
        [
            "Final_rank",
            "Design",
            "Rejected_no_interface",

            "RMSD_A",
            "Binder_pLDDT",
            "ipTM",
            "Interface_PAE",

            "Rosetta_dG_REU",
            "dSASA_A2",
            "Packstat",
            "Unsat_Hbond",

            "Min_AB_A",
            "Contacts_lt5A",

            "Weighted_rank_score"
        ]
    ]
)


# ============================================================
# 11) Save
# ============================================================

OUT = "/content/final_binder_ranking.csv"

df.to_csv(
    OUT,
    index=False
)

print("\n✅ Saved:")
print(OUT)

====================================================================================================
FINAL BINDER RANKING
====================================================================================================

,Final_rank,Design,Rejected_no_interface,RMSD_A,Binder_pLDDT,ipTM,Interface_PAE,Rosetta_dG_REU,dSASA_A2,Packstat,Unsat_Hbond,Min_AB_A,Contacts_lt5A,Weighted_rank_score
2,1.0,design_2,False,6.384,44.253,0.11,27.063,-42.924,1801.518,0.602,8.0,2.105,1445,2.073
1,2.0,design_1,False,17.339,38.251,0.12,26.079,-67.808,2440.553,0.584,12.0,1.865,2216,2.236
3,3.0,design_3,False,4.937,43.121,0.10,27.396,-36.724,1175.386,0.672,4.0,1.798,1032,2.600
0,4.0,design_0,False,6.523,40.832,0.10,27.260,-32.826,1541.773,0.660,5.0,2.164,1267,3.091
4,NaN,design_4,True,4.330,44.980,0.09,27.494,0.000,0.000,0.000,0.0,12.980,0,NaN

✅ Saved:
/content/final_binder_ranking.csv